#!/usr/bin/env python3
"""Resolve the manuscript into plain Typst that another tool can read.

WHY THIS EXISTS. `paper.typ` is not self-contained Typst: it imports a
template, calls `#s()`, `#lit()`, `fig()` and `tbl()`, and pulls its identity
out of `config.typ`. Typst itself evaluates all of that. Nothing else does --
and "nothing else" now matters, because pandoc can read Typst and turn it into
a Word file with NATIVE equations or into LaTeX for a journal that demands it.
Pandoc's reader is a real evaluator, so it does not choke on the syntax; it
chokes on our helpers, which are ours to resolve.

So this writes `paper.resolved.typ`: the same manuscript with every helper
replaced by what it produces. One resolution step, feeding every export path.
The alternative -- teaching each exporter about `#s()` -- is how the word
count, the readability report and the narrator each grew their own copy of the
same logic, and how the same construct got fixed three separate times.

IT IS A BUILD ARTIFACT, exactly like stats-rendered.json: gitignored,
rewritten by every recipe that needs it, never edited by hand, and deleted
when its source is gone. Read it when a conversion looks wrong -- it is
precisely what the converter was fed.

WHAT IT RESOLVES, and why each one has to go:

    #s("id") / #n("id")   the value. Left alone, pandoc reports `Identifier
                          "s" not found` and stops.
    #lit("2.2")           the literal, as typed.
    #todo("...")          REFUSED, not stripped. `just paper` panics on an
                          unresolved note; an export is a real deliverable
                          too, so it gets the same answer rather than a
                          quietly cleaner file.
    fig("id", width: 70%) image("figures/x.png", width: 70%), from assets.json
    tbl("id")             the generated table's source, inlined
    #refn(<x>)            ref(<x>): the project helper is a `#let` in the
                          preamble this file replaces
    @fig:x  @sec:x        #ref(<fig:x>). THIS ONE IS NOT COSMETIC: pandoc
                          reads `@fig` as a CITATION KEY and leaves `:x` as
                          stray text, so a cross-reference silently becomes
                          the words "[fig]:x" in the output. Only float and
                          section prefixes are rewritten; every other @key is
                          a real citation and must stay one.

Front matter is queried out of `config.typ` with `typst query` -- real Typst
evaluating the real file -- rather than parsed with a regex here. The template
itself is dropped: a converter cannot use Typst layout primitives, and a
journal supplies its own class file anyway.

Usage:  just resolve            # -> paper.resolved.typ
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

# The manuscript root, one level up: this file lives in tools/.
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

import readability  # noqa: E402
import typst_prose  # noqa: E402

OUT = ROOT / "paper.resolved.typ"
ASSETS = ROOT / "assets.json"

ABOUT = ("// GENERATED by tools/resolve_typst.py -- do not edit, do not commit.\n"
         "// The manuscript with every helper resolved, for pandoc. Edit\n"
         "// paper.typ / si-body.typ, or the analysis behind the numbers.\n")

# Label prefixes that are CROSS-REFERENCES rather than citation keys. `tab` is
# here because it is a common project convention (koth labels every table that
# way) and a manuscript using it would otherwise have every table reference
# silently turn into prose.
FLOAT_PREFIX = ("fig", "tbl", "tab", "eq", "sec")


class ResolveError(Exception):
    """The manuscript cannot be resolved into plain Typst."""


def _strip_comments(src: str) -> str:
    """Drop whole-line Typst comments.

    Whole-line only -- the same pattern readability.clean uses -- because a
    bare `//` inside a URL is not a comment. Applied to the manuscript AND to
    every generated table inlined into it: those carry an "AUTO-GENERATED"
    header, and inlining one into a `#figure(...)` argument put a comment
    inside a call, which pandoc's reader rejects outright.
    """
    return re.sub(r"(?m)^\s*//.*$", "", src)


def _query_front_matter() -> dict:
    """Title, authors and affiliations, evaluated by Typst itself.

    A regex over config.typ would be the obvious shortcut and the wrong one:
    the author line is BUILT there (initials, suffixes, particles -- see
    surname-of), so only Typst knows what it comes to. This asks Typst.
    """
    probe = ('#import "/config.typ": paper-title, paper-authors, '
             'paper-affiliations, paper-date\n'
             "#metadata((title: paper-title, "
             "authors: paper-authors.map(a => a.name), "
             "affils: paper-affiliations, date: paper-date)) <rmeta>\n")
    with tempfile.NamedTemporaryFile("w", suffix=".typ", dir=ROOT,
                                     delete=False) as fh:
        fh.write(probe)
        tmp = Path(fh.name)
    try:
        proc = subprocess.run(
            ["typst", "query", "--root", str(ROOT), str(tmp), "<rmeta>",
             "--field", "value", "--one"],
            capture_output=True, text=True, cwd=ROOT)
        if proc.returncode != 0:
            raise ResolveError(
                f"could not read the front matter out of config.typ: "
                f"{proc.stderr.strip().splitlines()[-1] if proc.stderr.strip() else '?'}")
        return json.loads(proc.stdout)
    finally:
        tmp.unlink(missing_ok=True)


def _abstract() -> str:
    """The abstract's SOURCE, from `#let paper-abstract = [...]`.

    Content, not a string, so it cannot come back through `typst query` as
    metadata. Taken as source text and handed on unresolved -- it is prose,
    and the notation pass below resolves whatever it contains.
    """
    raw = (ROOT / "config.typ").read_text()
    m = re.search(r"#let\s+paper-abstract\s*=\s*\[", raw)
    if not m:
        return ""
    depth, start = 0, m.end() - 1
    for i in range(start, len(raw)):
        if raw[i] == "[":
            depth += 1
        elif raw[i] == "]":
            depth -= 1
            if depth == 0:
                return raw[start + 1:i].strip()
    return ""


def resolve_notation(src: str, assets: dict, where: str) -> str:
    """Replace every project helper with what Typst would render for it."""
    # A note that cannot ship must not ship through a side door either.
    todo = re.search(typst_prose.TODO, src)
    if todo:
        raise ResolveError(
            f'unresolved #todo("{todo.group(1)}") in {where}. An export is a '
            f"deliverable: resolve the note and delete the call, exactly as "
            f"`just paper` requires.")

    # Comments go FIRST. si-body.typ documents its own usage with a literal
    # `#s("id")` in a comment block, and resolving that asked stats.json for a
    # value named "id".
    src = _strip_comments(src)

    src = typst_prose.resolve_stats(src)
    src = typst_prose.resolve_lit(src)

    def asset(m: re.Match) -> str:
        kind, id, args = m.group(1), m.group(2), m.group(3) or ""
        if id not in assets:
            raise ResolveError(
                f"{where} references {kind}(\"{id}\"), which assets.json does "
                f"not declare -- run: just assets")
        path = assets[id]["path"]
        if kind == "fig":
            return f'image("{path}"{args})'
        # A table is inlined rather than left as `include`: the generated file
        # is small, it is ours, and one fewer path for the converter to
        # resolve is one fewer way for the export to lose a table silently.
        target = ROOT / path
        if not target.is_file():
            raise ResolveError(f"{where}: {path} is missing -- run: just assets")
        # Wrapped in content brackets, and that is semantic rather than
        # cosmetic. `tbl()` resolves to `include`, and an include brings in
        # MARKUP -- where a generated table's leading `#table(` is correct.
        # Pasting that text straight into `#figure(...)`'s argument list drops
        # it into CODE mode, where a leading `#` is a syntax error. The
        # brackets put it back in markup, which is what include meant.
        return "[\n" + _strip_comments(target.read_text()).strip() + "\n]"

    src = typst_prose.ASSET_CALL.sub(asset, src)

    # The project's own bare-number reference helper, defined in the preamble
    # this file replaces.
    #
    # The `,?` is load-bearing and was missing from the first draft, which
    # then died on a real manuscript at `#refn(\n  <tbl:x>,\n)`. typstyle
    # breaks a long line INSIDE the call and leaves a trailing comma; every
    # shared pattern in typst_prose.py ends `,?\s*\)` for exactly this reason,
    # and this is the fourth time this repository has been bitten by it.
    src = re.sub(r"#?refn\(\s*(<[^>]+>)\s*,?\s*\)", r"#ref(\1)", src)

    # @fig:x -> #ref(<fig:x>). See the module docstring: pandoc reads the @ as
    # citation syntax, so leaving these alone turns every cross-reference into
    # stray prose. Citations (@lovelace1843) are deliberately untouched.
    src = re.sub(rf"@({'|'.join(FLOAT_PREFIX)}):([A-Za-z0-9_-]+)",
                 r"#ref(<\1:\2>)", src)
    return src


def build() -> str:
    if not ASSETS.is_file():
        assets = {}
    else:
        assets = json.loads(ASSETS.read_text()).get("values", {})

    meta = _query_front_matter()
    body = readability.slice_body((ROOT / "paper.typ").read_text())
    body = resolve_notation(body, assets, "paper.typ")

    # The SI is read as its own file, exactly as readability.py and the
    # narrator read it. paper.typ DOES `#include "si-body.typ"`, but that line
    # sits outside the BODY markers -- back matter does, by this scaffold's
    # convention -- so slicing the body drops it. Following the include from
    # inside the body instead silently produced a manuscript with no SI and
    # therefore no tables, which is how this was found.
    si = ROOT / "si-body.typ"
    if si.is_file():
        body += "\n\n" + resolve_notation(si.read_text(), assets, "si-body.typ")

    # Any OTHER include inside the body is inlined where it stands.
    def inline(m: re.Match) -> str:
        target = ROOT / m.group(1)
        if not target.is_file():
            raise ResolveError(f"paper.typ includes {m.group(1)}, which is missing")
        return resolve_notation(target.read_text(), assets, m.group(1))

    body = re.sub(r'#include\s+"([^"]+)"', inline, body)

    authors = ", ".join(meta.get("authors", []))
    affils = "\n".join(f"{i + 1}. {a}" for i, a in
                       enumerate(meta.get("affils", [])))
    abstract = resolve_notation(_abstract(), assets, "config.typ (abstract)")

    return (
        f"{ABOUT}\n"
        f"= {meta.get('title', '')}\n\n"
        f"{authors}\n\n"
        f"{affils}\n\n"
        f"== Abstract\n\n{abstract}\n\n"
        f"{body}\n"
    )


def main() -> int:
    try:
        OUT.write_text(build())
    except ResolveError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1
    n = len(OUT.read_text().splitlines())
    print(f"wrote {OUT.name} ({n:,} lines) -- plain Typst, for pandoc")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
