// AUTO-GENERATED by gen_development_table.py, do not edit by hand.
#set par(justify: false)
#table(columns: (0.7fr, 1.1fr, 1.3fr, 1fr, 1fr), inset: 4pt, align: left,
table.header([#text(size: 8pt)[Area]], [#text(size: 8pt)[Upstream Sage behavior]], [#text(size: 8pt)[Sage Plus change]], [#text(size: 8pt)[Motivation]], [#text(size: 8pt)[Expected consequence]]),
[#text(size: 8pt)[Input]], [#text(size: 8pt)[mzML, MGF, and Bruker readers]], [#text(size: 8pt)[mzMLb, Thermo RAW, peptide and cleavage inputs]], [#text(size: 8pt)[Broader data and digestion workflows]], [#text(size: 8pt)[Fewer conversions, new input contracts]],
[#text(size: 8pt)[Output]], [#text(size: 8pt)[TSV and optional Parquet, wide LFQ tables]], [#text(size: 8pt)[Typed Parquet, coordinates, long LFQ with nulls]], [#text(size: 8pt)[Explicit identities and missing signals]], [#text(size: 8pt)[Typed joins, revised consuming scripts]],
[#text(size: 8pt)[Storage]], [#text(size: 8pt)[Peptide arrays and dense modification vectors]], [#text(size: 8pt)[Protein spans and compact search structures]], [#text(size: 8pt)[Reduce allocation and record size]], [#text(size: 8pt)[Lower memory with possible access costs]],
[#text(size: 8pt)[Execution]], [#text(size: 8pt)[CLI searching and file batching]], [#text(size: 8pt)[Memory guards, API, events, isolated jobs]], [#text(size: 8pt)[Bound resources and expose run state]], [#text(size: 8pt)[Early rejection, inspectable failures]],
[#text(size: 8pt)[Modeling]], [#text(size: 8pt)[Isotope processing and linear prediction]], [#text(size: 8pt)[Scored envelopes, mass alignment, richer models]], [#text(size: 8pt)[Represent candidate evidence more fully]], [#text(size: 8pt)[Changed scores and acceptance thresholds]],
[#text(size: 8pt)[PTM]], [#text(size: 8pt)[Mass-based static and variable modifications]], [#text(size: 8pt)[PTM names, caps, neutral losses, site reports]], [#text(size: 8pt)[Explicit hypotheses and site ambiguity]], [#text(size: 8pt)[Bounded variants, new confidence endpoints]],
[#text(size: 8pt)[Quantification]], [#text(size: 8pt)[LFQ tracing and reporter-ion quantification]], [#text(size: 8pt)[Label channels, tracing controls, library export]], [#text(size: 8pt)[Extend quantification and result reuse]], [#text(size: 8pt)[More options, distinct validation needs]],
)
