// AUTO-GENERATED by gen_execution_table.py, do not edit by hand.
#set par(justify: false)
#table(columns: (2fr, 1fr, 1fr, 1fr, 1fr), inset: 4pt,
table.header([Workload], [Engine], [Attempts], [Completed], [Failed]),
[#text(size: 8pt)[Peptide entrapment]], [#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[12]], [#text(size: 8pt)[12]], [#text(size: 8pt)[0]],
[#text(size: 8pt)[Peptide entrapment]], [#text(size: 8pt)[Sage]], [#text(size: 8pt)[12]], [#text(size: 8pt)[12]], [#text(size: 8pt)[0]],
[#text(size: 8pt)[Local standard and modified]], [#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[8]], [#text(size: 8pt)[8]], [#text(size: 8pt)[0]],
[#text(size: 8pt)[Local standard and modified]], [#text(size: 8pt)[Sage]], [#text(size: 8pt)[8]], [#text(size: 8pt)[8]], [#text(size: 8pt)[0]],
[#text(size: 8pt)[Synthetic phosphorylation]], [#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[2]], [#text(size: 8pt)[2]], [#text(size: 8pt)[0]],
[#text(size: 8pt)[Synthetic phosphorylation]], [#text(size: 8pt)[Sage]], [#text(size: 8pt)[2]], [#text(size: 8pt)[2]], [#text(size: 8pt)[0]],
[#text(size: 8pt)[Public identification]], [#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[6]], [#text(size: 8pt)[6]], [#text(size: 8pt)[0]],
[#text(size: 8pt)[Public identification]], [#text(size: 8pt)[Sage]], [#text(size: 8pt)[6]], [#text(size: 8pt)[6]], [#text(size: 8pt)[0]],
[#text(size: 8pt)[Public repeat timing]], [#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[8]], [#text(size: 8pt)[7]], [#text(size: 8pt)[1]],
[#text(size: 8pt)[Public repeat timing]], [#text(size: 8pt)[Sage]], [#text(size: 8pt)[8]], [#text(size: 8pt)[7]], [#text(size: 8pt)[1]],
[#text(size: 8pt)[Label-free quantification]], [#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[1]], [#text(size: 8pt)[1]], [#text(size: 8pt)[0]],
[#text(size: 8pt)[Label-free quantification]], [#text(size: 8pt)[Sage]], [#text(size: 8pt)[1]], [#text(size: 8pt)[1]], [#text(size: 8pt)[0]],
[#text(size: 8pt)[Worker scaling]], [#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[16]], [#text(size: 8pt)[16]], [#text(size: 8pt)[0]],
[#text(size: 8pt)[Worker scaling]], [#text(size: 8pt)[Sage]], [#text(size: 8pt)[16]], [#text(size: 8pt)[16]], [#text(size: 8pt)[0]],
)
