// AUTO-GENERATED by gen_matched_fdp_table.py, do not edit by hand.
#table(columns: 5, inset: 4pt, align: left,
table.header([#text(size: 8pt)[Study]], [#text(size: 8pt)[Engine]], [#text(size: 8pt)[Mean target peptides]], [#text(size: 8pt)[FDP range (%)]], [#text(size: 8pt)[q-value range (%)]]),
[#text(size: 8pt)[HEK]], [#text(size: 8pt)[Sage]], [#text(size: 8pt)[10,046.2]], [#text(size: 8pt)[0.983 to 0.999]], [#text(size: 8pt)[0.810 to 1.172]],
[#text(size: 8pt)[HEK]], [#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[10,060.0]], [#text(size: 8pt)[0.971 to 0.997]], [#text(size: 8pt)[0.802 to 1.115]],
[#text(size: 8pt)[Mixture]], [#text(size: 8pt)[Sage]], [#text(size: 8pt)[37,079.2]], [#text(size: 8pt)[0.996 to 0.999]], [#text(size: 8pt)[0.907 to 1.127]],
[#text(size: 8pt)[Mixture]], [#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[37,120.2]], [#text(size: 8pt)[0.973 to 1.000]], [#text(size: 8pt)[0.795 to 1.025]],
)
