// AUTO-GENERATED by scripts/gen_prefilter_sweep_table.py -- do not edit by hand.
#table(
  columns: 8,
  align: (right, right, right, right, right, right, right, right),
  inset: 2.6pt,
  table.header(
    [#text(size: 6.4pt, weight: "bold")[Min. matches]], [#text(size: 6.4pt, weight: "bold")[Peaks]], [#text(size: 6.4pt, weight: "bold")[Kept (%)]], [#text(size: 6.4pt, weight: "bold")[Prefilter (s)]], [#text(size: 6.4pt, weight: "bold")[Wall (s)]], [#text(size: 6.4pt, weight: "bold")[Peak RSS (GiB)]], [#text(size: 6.4pt, weight: "bold")[PSMs]], [#text(size: 6.4pt, weight: "bold")[Entrapment FDP (%)]],
  ),
    [#text(size: 6.4pt)[1]], [#text(size: 6.4pt)[all]], [#text(size: 6.4pt)[76.3]], [#text(size: 6.4pt)[28.7]], [#text(size: 6.4pt)[132.6]], [#text(size: 6.4pt)[10.00]], [#text(size: 6.4pt)[16,155]], [#text(size: 6.4pt)[1.19]],
    [#text(size: 6.4pt)[1]], [#text(size: 6.4pt)[75]], [#text(size: 6.4pt)[72.1]], [#text(size: 6.4pt)[30.6]], [#text(size: 6.4pt)[130.9]], [#text(size: 6.4pt)[9.61]], [#text(size: 6.4pt)[16,153]], [#text(size: 6.4pt)[1.19]],
    [#text(size: 6.4pt)[1]], [#text(size: 6.4pt)[50]], [#text(size: 6.4pt)[67.2]], [#text(size: 6.4pt)[31.1]], [#text(size: 6.4pt)[127.4]], [#text(size: 6.4pt)[9.07]], [#text(size: 6.4pt)[16,163]], [#text(size: 6.4pt)[1.20]],
    [#text(size: 6.4pt)[2]], [#text(size: 6.4pt)[all]], [#text(size: 6.4pt)[51.3]], [#text(size: 6.4pt)[45.7]], [#text(size: 6.4pt)[128.9]], [#text(size: 6.4pt)[7.47]], [#text(size: 6.4pt)[16,118]], [#text(size: 6.4pt)[1.34]],
    [#text(size: 6.4pt)[2]], [#text(size: 6.4pt)[75]], [#text(size: 6.4pt)[32.6]], [#text(size: 6.4pt)[48.0]], [#text(size: 6.4pt)[115.6]], [#text(size: 6.4pt)[5.80]], [#text(size: 6.4pt)[16,062]], [#text(size: 6.4pt)[1.42]],
    [#text(size: 6.4pt)[2]], [#text(size: 6.4pt)[50]], [#text(size: 6.4pt)[21.8]], [#text(size: 6.4pt)[46.8]], [#text(size: 6.4pt)[106.5]], [#text(size: 6.4pt)[5.18]], [#text(size: 6.4pt)[16,025]], [#text(size: 6.4pt)[1.43]],
    [#text(size: 6.4pt)[3]], [#text(size: 6.4pt)[all]], [#text(size: 6.4pt)[18.7]], [#text(size: 6.4pt)[54.5]], [#text(size: 6.4pt)[112.1]], [#text(size: 6.4pt)[4.98]], [#text(size: 6.4pt)[16,038]], [#text(size: 6.4pt)[1.35]],
    [#text(size: 6.4pt)[3]], [#text(size: 6.4pt)[75]], [#text(size: 6.4pt)[6.7]], [#text(size: 6.4pt)[52.6]], [#text(size: 6.4pt)[103.6]], [#text(size: 6.4pt)[4.65]], [#text(size: 6.4pt)[15,962]], [#text(size: 6.4pt)[1.32]],
    [#text(size: 6.4pt)[3]], [#text(size: 6.4pt)[50]], [#text(size: 6.4pt)[3.5]], [#text(size: 6.4pt)[49.3]], [#text(size: 6.4pt)[98.6]], [#text(size: 6.4pt)[4.73]], [#text(size: 6.4pt)[15,822]], [#text(size: 6.4pt)[1.34]],
    [#text(size: 6.4pt)[4]], [#text(size: 6.4pt)[all]], [#text(size: 6.4pt)[4.6]], [#text(size: 6.4pt)[56.9]], [#text(size: 6.4pt)[107.1]], [#text(size: 6.4pt)[4.78]], [#text(size: 6.4pt)[15,826]], [#text(size: 6.4pt)[1.27]],
    [#text(size: 6.4pt)[4]], [#text(size: 6.4pt)[75]], [#text(size: 6.4pt)[1.2]], [#text(size: 6.4pt)[52.9]], [#text(size: 6.4pt)[100.9]], [#text(size: 6.4pt)[4.63]], [#text(size: 6.4pt)[15,742]], [#text(size: 6.4pt)[1.35]],
    [#text(size: 6.4pt)[4]], [#text(size: 6.4pt)[50]], [#text(size: 6.4pt)[0.6]], [#text(size: 6.4pt)[49.7]], [#text(size: 6.4pt)[97.4]], [#text(size: 6.4pt)[4.60]], [#text(size: 6.4pt)[15,637]], [#text(size: 6.4pt)[1.48]],
    [#text(size: 6.4pt)[6]], [#text(size: 6.4pt)[all]], [#text(size: 6.4pt)[0.3]], [#text(size: 6.4pt)[57.4]], [#text(size: 6.4pt)[104.4]], [#text(size: 6.4pt)[4.60]], [#text(size: 6.4pt)[15,445]], [#text(size: 6.4pt)[1.23]],
    [#text(size: 6.4pt)[6]], [#text(size: 6.4pt)[75]], [#text(size: 6.4pt)[0.1]], [#text(size: 6.4pt)[53.1]], [#text(size: 6.4pt)[100.4]], [#text(size: 6.4pt)[4.73]], [#text(size: 6.4pt)[15,208]], [#text(size: 6.4pt)[1.31]],
    [#text(size: 6.4pt)[6]], [#text(size: 6.4pt)[50]], [#text(size: 6.4pt)[0.1]], [#text(size: 6.4pt)[49.5]], [#text(size: 6.4pt)[95.5]], [#text(size: 6.4pt)[4.53]], [#text(size: 6.4pt)[14,640]], [#text(size: 6.4pt)[1.26]],
)
