// AUTO-GENERATED by scripts/gen_prefilter_sweep_table.py -- do not edit by hand.
#table(
  columns: 8,
  align: (right, right, right, right, right, right, right, right),
  inset: 2.6pt,
  table.header(
    [#text(size: 6.4pt, weight: "bold")[Min. matches]], [#text(size: 6.4pt, weight: "bold")[Peaks]], [#text(size: 6.4pt, weight: "bold")[Kept (%)]], [#text(size: 6.4pt, weight: "bold")[Prefilter (s)]], [#text(size: 6.4pt, weight: "bold")[Wall (s)]], [#text(size: 6.4pt, weight: "bold")[Peak RSS (GiB)]], [#text(size: 6.4pt, weight: "bold")[PSMs]], [#text(size: 6.4pt, weight: "bold")[Entrapment FDP (%)]],
  ),
    [#text(size: 6.4pt)[1]], [#text(size: 6.4pt)[all]], [#text(size: 6.4pt)[76.2]], [#text(size: 6.4pt)[26.7]], [#text(size: 6.4pt)[66.4]], [#text(size: 6.4pt)[11.51]], [#text(size: 6.4pt)[16,524]], [#text(size: 6.4pt)[1.46]],
    [#text(size: 6.4pt)[1]], [#text(size: 6.4pt)[75]], [#text(size: 6.4pt)[72.0]], [#text(size: 6.4pt)[26.6]], [#text(size: 6.4pt)[64.7]], [#text(size: 6.4pt)[10.90]], [#text(size: 6.4pt)[16,537]], [#text(size: 6.4pt)[1.48]],
    [#text(size: 6.4pt)[1]], [#text(size: 6.4pt)[50]], [#text(size: 6.4pt)[67.1]], [#text(size: 6.4pt)[27.4]], [#text(size: 6.4pt)[63.9]], [#text(size: 6.4pt)[10.19]], [#text(size: 6.4pt)[16,547]], [#text(size: 6.4pt)[1.57]],
    [#text(size: 6.4pt)[2]], [#text(size: 6.4pt)[all]], [#text(size: 6.4pt)[51.3]], [#text(size: 6.4pt)[43.0]], [#text(size: 6.4pt)[70.0]], [#text(size: 6.4pt)[7.88]], [#text(size: 6.4pt)[16,516]], [#text(size: 6.4pt)[1.52]],
    [#text(size: 6.4pt)[2]], [#text(size: 6.4pt)[75]], [#text(size: 6.4pt)[32.5]], [#text(size: 6.4pt)[42.4]], [#text(size: 6.4pt)[59.8]], [#text(size: 6.4pt)[5.22]], [#text(size: 6.4pt)[16,456]], [#text(size: 6.4pt)[1.58]],
    [#text(size: 6.4pt)[2]], [#text(size: 6.4pt)[50]], [#text(size: 6.4pt)[21.8]], [#text(size: 6.4pt)[39.8]], [#text(size: 6.4pt)[51.5]], [#text(size: 6.4pt)[3.68]], [#text(size: 6.4pt)[16,386]], [#text(size: 6.4pt)[1.60]],
    [#text(size: 6.4pt)[3]], [#text(size: 6.4pt)[all]], [#text(size: 6.4pt)[18.7]], [#text(size: 6.4pt)[49.6]], [#text(size: 6.4pt)[60.4]], [#text(size: 6.4pt)[3.27]], [#text(size: 6.4pt)[16,378]], [#text(size: 6.4pt)[1.65]],
    [#text(size: 6.4pt)[3]], [#text(size: 6.4pt)[75]], [#text(size: 6.4pt)[6.7]], [#text(size: 6.4pt)[44.7]], [#text(size: 6.4pt)[50.6]], [#text(size: 6.4pt)[1.57]], [#text(size: 6.4pt)[16,326]], [#text(size: 6.4pt)[1.68]],
    [#text(size: 6.4pt)[3]], [#text(size: 6.4pt)[50]], [#text(size: 6.4pt)[3.4]], [#text(size: 6.4pt)[40.7]], [#text(size: 6.4pt)[45.2]], [#text(size: 6.4pt)[1.29]], [#text(size: 6.4pt)[16,244]], [#text(size: 6.4pt)[1.59]],
    [#text(size: 6.4pt)[4]], [#text(size: 6.4pt)[all]], [#text(size: 6.4pt)[4.6]], [#text(size: 6.4pt)[51.2]], [#text(size: 6.4pt)[56.2]], [#text(size: 6.4pt)[1.35]], [#text(size: 6.4pt)[16,211]], [#text(size: 6.4pt)[1.57]],
    [#text(size: 6.4pt)[4]], [#text(size: 6.4pt)[75]], [#text(size: 6.4pt)[1.2]], [#text(size: 6.4pt)[45.0]], [#text(size: 6.4pt)[48.5]], [#text(size: 6.4pt)[1.13]], [#text(size: 6.4pt)[16,163]], [#text(size: 6.4pt)[1.56]],
    [#text(size: 6.4pt)[4]], [#text(size: 6.4pt)[50]], [#text(size: 6.4pt)[0.6]], [#text(size: 6.4pt)[40.7]], [#text(size: 6.4pt)[43.8]], [#text(size: 6.4pt)[1.10]], [#text(size: 6.4pt)[16,034]], [#text(size: 6.4pt)[1.66]],
    [#text(size: 6.4pt)[6]], [#text(size: 6.4pt)[all]], [#text(size: 6.4pt)[0.3]], [#text(size: 6.4pt)[51.8]], [#text(size: 6.4pt)[54.5]], [#text(size: 6.4pt)[1.10]], [#text(size: 6.4pt)[15,702]], [#text(size: 6.4pt)[1.43]],
    [#text(size: 6.4pt)[6]], [#text(size: 6.4pt)[75]], [#text(size: 6.4pt)[0.1]], [#text(size: 6.4pt)[45.6]], [#text(size: 6.4pt)[48.0]], [#text(size: 6.4pt)[1.06]], [#text(size: 6.4pt)[15,364]], [#text(size: 6.4pt)[1.36]],
    [#text(size: 6.4pt)[6]], [#text(size: 6.4pt)[50]], [#text(size: 6.4pt)[0.1]], [#text(size: 6.4pt)[41.1]], [#text(size: 6.4pt)[43.5]], [#text(size: 6.4pt)[1.15]], [#text(size: 6.4pt)[14,811]], [#text(size: 6.4pt)[1.34]],
)
