// AUTO-GENERATED by scripts/gen_ptm_library_table.py -- do not edit by hand.
#table(
  columns: 7,
  align: (right, right, right, right, right, right, right),
  inset: 3pt,
  table.header(
    [#text(size: 6.7pt, weight: "bold")[Condition]], [#text(size: 6.7pt, weight: "bold")[Wall]], [#text(size: 6.7pt, weight: "bold")[Peak RSS]], [#text(size: 6.7pt, weight: "bold")[DB peptides]], [#text(size: 6.7pt, weight: "bold")[Fragments]], [#text(size: 6.7pt, weight: "bold")[PSMs]], [#text(size: 6.7pt, weight: "bold")[Peptides]],
  ),
    [#text(size: 6.7pt)[Conventional]], [#text(size: 6.7pt)[6.07 s]], [#text(size: 6.7pt)[1,499.7 MiB]], [#text(size: 6.7pt)[2,803,578]], [#text(size: 6.7pt)[80,833,042]], [#text(size: 6.7pt)[2,203]], [#text(size: 6.7pt)[1,409]],
    [#text(size: 6.7pt)[Exhaustive]], [#text(size: 6.7pt)[24.96 s]], [#text(size: 6.7pt)[4,605.5 MiB]], [#text(size: 6.7pt)[10,787,909]], [#text(size: 6.7pt)[317,149,388]], [#text(size: 6.7pt)[2,267]], [#text(size: 6.7pt)[1,497]],
    [#text(size: 6.7pt)[Library 0]], [#text(size: 6.7pt)[12.25 s]], [#text(size: 6.7pt)[1,584.1 MiB]], [#text(size: 6.7pt)[2,803,578]], [#text(size: 6.7pt)[80,833,042]], [#text(size: 6.7pt)[2,203]], [#text(size: 6.7pt)[1,409]],
    [#text(size: 6.7pt)[Library 50,000]], [#text(size: 6.7pt)[12.72 s]], [#text(size: 6.7pt)[1,681.8 MiB]], [#text(size: 6.7pt)[3,030,517]], [#text(size: 6.7pt)[89,341,256]], [#text(size: 6.7pt)[2,206]], [#text(size: 6.7pt)[1,412]],
    [#text(size: 6.7pt)[Library 200,000]], [#text(size: 6.7pt)[14.53 s]], [#text(size: 6.7pt)[2,085.5 MiB]], [#text(size: 6.7pt)[3,775,367]], [#text(size: 6.7pt)[117,638,808]], [#text(size: 6.7pt)[2,203]], [#text(size: 6.7pt)[1,414]],
    [#text(size: 6.7pt)[Library 500,000]], [#text(size: 6.7pt)[17.72 s]], [#text(size: 6.7pt)[2,826.1 MiB]], [#text(size: 6.7pt)[5,271,114]], [#text(size: 6.7pt)[172,112,992]], [#text(size: 6.7pt)[2,199]], [#text(size: 6.7pt)[1,420]],
)
