// AUTO-GENERATED by scripts/gen_benchmark_table.py -- do not edit by hand.
#table(
  columns: 7,
  align: (left, right, right, right, right, right, right),
  inset: 3pt,
  table.header(
    [#text(size: 6.8pt, weight: "bold")[Workload]], [#text(size: 6.8pt, weight: "bold")[Sage wall]], [#text(size: 6.8pt, weight: "bold")[Plus wall]], [#text(size: 6.8pt, weight: "bold")[Wall change]], [#text(size: 6.8pt, weight: "bold")[Sage RSS]], [#text(size: 6.8pt, weight: "bold")[Plus RSS]], [#text(size: 6.8pt, weight: "bold")[RSS change]],
  ),
    [#text(size: 6.8pt)[Conventional]], [#text(size: 6.8pt)[5.38 s]], [#text(size: 6.8pt)[6.45 s]], [#text(size: 6.8pt)[+19.9%]], [#text(size: 6.8pt)[1,911.4 MiB]], [#text(size: 6.8pt)[1,494.8 MiB]], [#text(size: 6.8pt)[-21.8%]],
    [#text(size: 6.8pt)[Common modifications]], [#text(size: 6.8pt)[11.94 s]], [#text(size: 6.8pt)[12.14 s]], [#text(size: 6.8pt)[+1.7%]], [#text(size: 6.8pt)[5,495.6 MiB]], [#text(size: 6.8pt)[3,698.5 MiB]], [#text(size: 6.8pt)[-32.7%]],
    [#text(size: 6.8pt)[Broad PTMs]], [#text(size: 6.8pt)[25.74 s]], [#text(size: 6.8pt)[29.07 s]], [#text(size: 6.8pt)[+12.9%]], [#text(size: 6.8pt)[12,278.0 MiB]], [#text(size: 6.8pt)[7,792.3 MiB]], [#text(size: 6.8pt)[-36.5%]],
)
