// AUTO-GENERATED by gen_report_table.py, do not edit by hand.
#table(columns: 5, inset: 4pt, align: left,
table.header([#text(size: 8pt)[HCD input]], [#text(size: 8pt)[Consistent sites]], [#text(size: 8pt)[Inconsistent sites]], [#text(size: 8pt)[Inconsistent (%)]], [#text(size: 8pt)[Jointly accepted sites]]),
[#text(size: 8pt)[1]], [#text(size: 8pt)[1172]], [#text(size: 8pt)[118]], [#text(size: 8pt)[9.15]], [#text(size: 8pt)[0]],
[#text(size: 8pt)[2]], [#text(size: 8pt)[880]], [#text(size: 8pt)[15]], [#text(size: 8pt)[1.68]], [#text(size: 8pt)[0]],
)
