// AUTO-GENERATED by gen_report_table.py, do not edit by hand.
#table(columns: 7, inset: 4pt, align: left,
table.header([#text(size: 8pt)[Engine]], [#text(size: 8pt)[Workers]], [#text(size: 8pt)[Completed trials]], [#text(size: 8pt)[Seconds]], [#text(size: 8pt)[Time range]], [#text(size: 8pt)[Peak MiB]], [#text(size: 8pt)[PSM range]]),
[#text(size: 8pt)[Sage]], [#text(size: 8pt)[1]], [#text(size: 8pt)[3]], [#text(size: 8pt)[40.05]], [#text(size: 8pt)[39.80 to 40.41]], [#text(size: 8pt)[1752.4]], [#text(size: 8pt)[16,866]],
[#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[1]], [#text(size: 8pt)[3]], [#text(size: 8pt)[41.65]], [#text(size: 8pt)[41.29 to 42.39]], [#text(size: 8pt)[1424.4]], [#text(size: 8pt)[16,917]],
[#text(size: 8pt)[Sage]], [#text(size: 8pt)[2]], [#text(size: 8pt)[3]], [#text(size: 8pt)[23.51]], [#text(size: 8pt)[23.13 to 23.92]], [#text(size: 8pt)[1798.0]], [#text(size: 8pt)[16,866]],
[#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[2]], [#text(size: 8pt)[3]], [#text(size: 8pt)[24.98]], [#text(size: 8pt)[24.37 to 25.08]], [#text(size: 8pt)[1424.6]], [#text(size: 8pt)[16,917]],
[#text(size: 8pt)[Sage]], [#text(size: 8pt)[4]], [#text(size: 8pt)[3]], [#text(size: 8pt)[15.36]], [#text(size: 8pt)[15.13 to 15.76]], [#text(size: 8pt)[2030.5]], [#text(size: 8pt)[16,866]],
[#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[4]], [#text(size: 8pt)[3]], [#text(size: 8pt)[14.76]], [#text(size: 8pt)[14.71 to 14.83]], [#text(size: 8pt)[1433.6]], [#text(size: 8pt)[16,917]],
[#text(size: 8pt)[Sage]], [#text(size: 8pt)[8]], [#text(size: 8pt)[3]], [#text(size: 8pt)[11.28]], [#text(size: 8pt)[11.19 to 11.37]], [#text(size: 8pt)[2125.2]], [#text(size: 8pt)[16,866]],
[#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[8]], [#text(size: 8pt)[3]], [#text(size: 8pt)[10.59]], [#text(size: 8pt)[10.50 to 10.63]], [#text(size: 8pt)[1494.8]], [#text(size: 8pt)[16,917]],
)
