// AUTO-GENERATED by gen_report_table.py, do not edit by hand.
#table(columns: 5, inset: 4pt, align: left,
table.header([#text(size: 8pt)[HCD input]], [#text(size: 8pt)[Consistent sites]], [#text(size: 8pt)[Inconsistent sites]], [#text(size: 8pt)[Inconsistent (%)]], [#text(size: 8pt)[Jointly accepted sites]]),
[#text(size: 8pt)[1]], [#text(size: 8pt)[1128]], [#text(size: 8pt)[15]], [#text(size: 8pt)[1.31]], [#text(size: 8pt)[1143]],
[#text(size: 8pt)[2]], [#text(size: 8pt)[876]], [#text(size: 8pt)[1]], [#text(size: 8pt)[0.11]], [#text(size: 8pt)[877]],
)
