// AUTO-GENERATED by gen_report_table.py, do not edit by hand.
#table(columns: 6, inset: 4pt, align: left,
table.header([#text(size: 8pt)[Engine]], [#text(size: 8pt)[Workers]], [#text(size: 8pt)[Seconds]], [#text(size: 8pt)[Time range]], [#text(size: 8pt)[Peak MiB]], [#text(size: 8pt)[PSM range]]),
[#text(size: 8pt)[Sage]], [#text(size: 8pt)[1]], [#text(size: 8pt)[39.17]], [#text(size: 8pt)[38.90 to 39.53]], [#text(size: 8pt)[1752.6]], [#text(size: 8pt)[16,866 to 16,866]],
[#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[1]], [#text(size: 8pt)[39.84]], [#text(size: 8pt)[39.01 to 39.95]], [#text(size: 8pt)[1423.7]], [#text(size: 8pt)[16,917 to 16,917]],
[#text(size: 8pt)[Sage]], [#text(size: 8pt)[2]], [#text(size: 8pt)[22.22]], [#text(size: 8pt)[21.83 to 22.78]], [#text(size: 8pt)[1791.7]], [#text(size: 8pt)[16,866 to 16,866]],
[#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[2]], [#text(size: 8pt)[23.18]], [#text(size: 8pt)[22.65 to 24.88]], [#text(size: 8pt)[1424.2]], [#text(size: 8pt)[16,917 to 16,917]],
[#text(size: 8pt)[Sage]], [#text(size: 8pt)[4]], [#text(size: 8pt)[14.48]], [#text(size: 8pt)[13.92 to 14.80]], [#text(size: 8pt)[2096.2]], [#text(size: 8pt)[16,866 to 16,866]],
[#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[4]], [#text(size: 8pt)[14.07]], [#text(size: 8pt)[13.99 to 14.20]], [#text(size: 8pt)[1424.7]], [#text(size: 8pt)[16,917 to 16,917]],
[#text(size: 8pt)[Sage]], [#text(size: 8pt)[8]], [#text(size: 8pt)[10.42]], [#text(size: 8pt)[10.26 to 10.54]], [#text(size: 8pt)[2106.4]], [#text(size: 8pt)[16,866 to 16,866]],
[#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[8]], [#text(size: 8pt)[9.82]], [#text(size: 8pt)[9.75 to 9.97]], [#text(size: 8pt)[1500.7]], [#text(size: 8pt)[16,917 to 16,917]],
)
