// AUTO-GENERATED by gen_report_table.py, do not edit by hand.
#table(columns: 7, inset: 4pt, align: left,
table.header([#text(size: 8pt)[Engine]], [#text(size: 8pt)[Workers]], [#text(size: 8pt)[Completed trials]], [#text(size: 8pt)[Seconds]], [#text(size: 8pt)[Time range]], [#text(size: 8pt)[Peak MiB]], [#text(size: 8pt)[PSM range]]),
[#text(size: 8pt)[Sage]], [#text(size: 8pt)[1]], [#text(size: 8pt)[3]], [#text(size: 8pt)[38.10]], [#text(size: 8pt)[37.73 to 38.50]], [#text(size: 8pt)[1752.5]], [#text(size: 8pt)[16,866]],
[#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[1]], [#text(size: 8pt)[3]], [#text(size: 8pt)[37.01]], [#text(size: 8pt)[36.98 to 38.09]], [#text(size: 8pt)[1438.3]], [#text(size: 8pt)[17,013]],
[#text(size: 8pt)[Sage]], [#text(size: 8pt)[2]], [#text(size: 8pt)[3]], [#text(size: 8pt)[22.01]], [#text(size: 8pt)[21.94 to 22.10]], [#text(size: 8pt)[1793.4]], [#text(size: 8pt)[16,866]],
[#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[2]], [#text(size: 8pt)[3]], [#text(size: 8pt)[22.32]], [#text(size: 8pt)[22.09 to 22.36]], [#text(size: 8pt)[1439.5]], [#text(size: 8pt)[17,013]],
[#text(size: 8pt)[Sage]], [#text(size: 8pt)[4]], [#text(size: 8pt)[3]], [#text(size: 8pt)[13.99]], [#text(size: 8pt)[13.91 to 14.65]], [#text(size: 8pt)[2089.4]], [#text(size: 8pt)[16,866]],
[#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[4]], [#text(size: 8pt)[3]], [#text(size: 8pt)[13.86]], [#text(size: 8pt)[13.84 to 14.52]], [#text(size: 8pt)[1441.0]], [#text(size: 8pt)[17,013]],
[#text(size: 8pt)[Sage]], [#text(size: 8pt)[8]], [#text(size: 8pt)[3]], [#text(size: 8pt)[10.26]], [#text(size: 8pt)[9.90 to 10.32]], [#text(size: 8pt)[2117.8]], [#text(size: 8pt)[16,866]],
[#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[8]], [#text(size: 8pt)[3]], [#text(size: 8pt)[10.25]], [#text(size: 8pt)[10.07 to 10.27]], [#text(size: 8pt)[1444.0]], [#text(size: 8pt)[17,013]],
)
