// AUTO-GENERATED by gen_report_table.py, do not edit by hand.
#table(columns: 7, inset: 4pt, align: left,
table.header([#text(size: 8pt)[Engine]], [#text(size: 8pt)[Species]], [#text(size: 8pt)[Ratio pairs]], [#text(size: 8pt)[Bias]], [#text(size: 8pt)[Abs. error]], [#text(size: 8pt)[CV (%)]], [#text(size: 8pt)[Missing (%)]]),
[#text(size: 8pt)[Sage]], [#text(size: 8pt)[human]], [#text(size: 8pt)[35,975]], [#text(size: 8pt)[-0.044]], [#text(size: 8pt)[0.239]], [#text(size: 8pt)[29.9]], [#text(size: 8pt)[0.859]],
[#text(size: 8pt)[Sage]], [#text(size: 8pt)[yeast]], [#text(size: 8pt)[10,583]], [#text(size: 8pt)[-0.142]], [#text(size: 8pt)[0.275]], [#text(size: 8pt)[25.9]], [#text(size: 8pt)[0.005]],
[#text(size: 8pt)[Sage]], [#text(size: 8pt)[ecoli]], [#text(size: 8pt)[1,866]], [#text(size: 8pt)[+0.183]], [#text(size: 8pt)[0.451]], [#text(size: 8pt)[27.4]], [#text(size: 8pt)[0.054]],
[#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[human]], [#text(size: 8pt)[47,987]], [#text(size: 8pt)[-0.039]], [#text(size: 8pt)[0.209]], [#text(size: 8pt)[29.5]], [#text(size: 8pt)[0.333]],
[#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[yeast]], [#text(size: 8pt)[12,543]], [#text(size: 8pt)[-0.142]], [#text(size: 8pt)[0.273]], [#text(size: 8pt)[26.1]], [#text(size: 8pt)[0.004]],
[#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[ecoli]], [#text(size: 8pt)[2,284]], [#text(size: 8pt)[+0.184]], [#text(size: 8pt)[0.466]], [#text(size: 8pt)[26.7]], [#text(size: 8pt)[0.044]],
)
