// AUTO-GENERATED by gen_report_table.py, do not edit by hand.
#table(columns: 5, inset: 4pt, align: left,
table.header([#text(size: 8pt)[Species]], [#text(size: 8pt)[Shared pairs]], [#text(size: 8pt)[Sage abs. error]], [#text(size: 8pt)[Plus abs. error]], [#text(size: 8pt)[Median ratio difference]]),
[#text(size: 8pt)[ecoli]], [#text(size: 8pt)[1,776]], [#text(size: 8pt)[0.450]], [#text(size: 8pt)[0.433]], [#text(size: 8pt)[0.013]],
[#text(size: 8pt)[human]], [#text(size: 8pt)[33,715]], [#text(size: 8pt)[0.234]], [#text(size: 8pt)[0.199]], [#text(size: 8pt)[0.019]],
[#text(size: 8pt)[yeast]], [#text(size: 8pt)[10,171]], [#text(size: 8pt)[0.274]], [#text(size: 8pt)[0.263]], [#text(size: 8pt)[0.013]],
)
