// AUTO-GENERATED by gen_report_table.py, do not edit by hand.
#table(columns: 5, inset: 4pt, align: left,
table.header([#text(size: 8pt)[Species]], [#text(size: 8pt)[Shared pairs]], [#text(size: 8pt)[Sage abs. error]], [#text(size: 8pt)[Plus abs. error]], [#text(size: 8pt)[Median ratio difference]]),
[#text(size: 8pt)[ecoli]], [#text(size: 8pt)[1,788]], [#text(size: 8pt)[0.448]], [#text(size: 8pt)[0.447]], [#text(size: 8pt)[0.007]],
[#text(size: 8pt)[human]], [#text(size: 8pt)[33,792]], [#text(size: 8pt)[0.237]], [#text(size: 8pt)[0.235]], [#text(size: 8pt)[0.007]],
[#text(size: 8pt)[yeast]], [#text(size: 8pt)[10,183]], [#text(size: 8pt)[0.273]], [#text(size: 8pt)[0.271]], [#text(size: 8pt)[0.006]],
)
