// AUTO-GENERATED by gen_scientific_table.py, do not edit by hand.
#table(columns: 5, inset: 5pt, align: left,
table.header([#text(size: 8pt)[Study]], [#text(size: 8pt)[Sage FDP (%)]], [#text(size: 8pt)[Plus FDP (%)]], [#text(size: 8pt)[Difference (pp)]], [#text(size: 8pt)[Interval (pp)]]),
[#text(size: 8pt)[HEK]], [#text(size: 8pt)[1.017]], [#text(size: 8pt)[0.963]], [#text(size: 8pt)[-0.054]], [#text(size: 8pt)[-0.152 to +0.005]],
[#text(size: 8pt)[Mixture]], [#text(size: 8pt)[1.027]], [#text(size: 8pt)[1.094]], [#text(size: 8pt)[+0.067]], [#text(size: 8pt)[+0.003 to +0.097]],
)
