// AUTO-GENERATED by gen_scientific_table.py, do not edit by hand.
#table(columns: 5, inset: 5pt, align: left,
table.header([#text(size: 8pt)[Study]], [#text(size: 8pt)[Engine]], [#text(size: 8pt)[Searches]], [#text(size: 8pt)[Median seconds]], [#text(size: 8pt)[Median peak MiB]]),
[#text(size: 8pt)[HEK]], [#text(size: 8pt)[Sage]], [#text(size: 8pt)[6]], [#text(size: 8pt)[19.30]], [#text(size: 8pt)[3866.4]],
[#text(size: 8pt)[HEK]], [#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[6]], [#text(size: 8pt)[22.98]], [#text(size: 8pt)[3148.8]],
[#text(size: 8pt)[Mixture]], [#text(size: 8pt)[Sage]], [#text(size: 8pt)[6]], [#text(size: 8pt)[40.83]], [#text(size: 8pt)[5330.8]],
[#text(size: 8pt)[Mixture]], [#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[6]], [#text(size: 8pt)[48.39]], [#text(size: 8pt)[4337.7]],
)
