// AUTO-GENERATED by gen_scientific_table.py, do not edit by hand.
#table(columns: 5, inset: 5pt, align: left,
table.header([#text(size: 8pt)[Workload]], [#text(size: 8pt)[Engine]], [#text(size: 8pt)[Seconds]], [#text(size: 8pt)[Peak MiB]], [#text(size: 8pt)[Target PSMs]]),
[#text(size: 8pt)[standard]], [#text(size: 8pt)[Sage]], [#text(size: 8pt)[6.14]], [#text(size: 8pt)[1915.6]], [#text(size: 8pt)[2214]],
[#text(size: 8pt)[standard]], [#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[6.89]], [#text(size: 8pt)[1491.3]], [#text(size: 8pt)[2203]],
[#text(size: 8pt)[common-mods]], [#text(size: 8pt)[Sage]], [#text(size: 8pt)[12.95]], [#text(size: 8pt)[5471.7]], [#text(size: 8pt)[2266]],
[#text(size: 8pt)[common-mods]], [#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[15.52]], [#text(size: 8pt)[3604.6]], [#text(size: 8pt)[2270]],
)
