// AUTO-GENERATED by gen_scientific_table.py, do not edit by hand.
#table(columns: 5, inset: 5pt, align: left,
table.header([#text(size: 8pt)[Study]], [#text(size: 8pt)[Sage FDP (%)]], [#text(size: 8pt)[Plus FDP (%)]], [#text(size: 8pt)[Difference (pp)]], [#text(size: 8pt)[Interval (pp)]]),
[#text(size: 8pt)[HEK]], [#text(size: 8pt)[1.017]], [#text(size: 8pt)[0.998]], [#text(size: 8pt)[-0.019]], [#text(size: 8pt)[-0.083 to +0.054]],
[#text(size: 8pt)[Mixture]], [#text(size: 8pt)[1.029]], [#text(size: 8pt)[1.057]], [#text(size: 8pt)[+0.028]], [#text(size: 8pt)[-0.039 to +0.066]],
)
