// AUTO-GENERATED by gen_scientific_table.py, do not edit by hand.
#table(columns: 6, inset: 5pt, align: left,
table.header([#text(size: 8pt)[Study]], [#text(size: 8pt)[Engine]], [#text(size: 8pt)[Completed trials]], [#text(size: 8pt)[Seconds (range)]], [#text(size: 8pt)[Peak MiB]], [#text(size: 8pt)[Target PSMs]]),
[#text(size: 8pt)[PXD001468]], [#text(size: 8pt)[Sage]], [#text(size: 8pt)[3/3]], [#text(size: 8pt)[10.11 (10.00–10.36)]], [#text(size: 8pt)[2127.0]], [#text(size: 8pt)[16,866]],
[#text(size: 8pt)[PXD001468]], [#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[3/3]], [#text(size: 8pt)[10.10 (9.96–10.24)]], [#text(size: 8pt)[1444.8]], [#text(size: 8pt)[17,013]],
[#text(size: 8pt)[PXD028735]], [#text(size: 8pt)[Sage]], [#text(size: 8pt)[3/3]], [#text(size: 8pt)[27.64 (26.27–29.35)]], [#text(size: 8pt)[3079.5]], [#text(size: 8pt)[55,457]],
[#text(size: 8pt)[PXD028735]], [#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[3/3]], [#text(size: 8pt)[25.36 (24.93–25.42)]], [#text(size: 8pt)[2422.8]], [#text(size: 8pt)[56,057]],
)
