// AUTO-GENERATED by gen_scientific_table.py, do not edit by hand.
#table(columns: 5, inset: 5pt, align: left,
table.header([#text(size: 8pt)[Study]], [#text(size: 8pt)[Engine]], [#text(size: 8pt)[Searches]], [#text(size: 8pt)[Median seconds]], [#text(size: 8pt)[Median peak MiB]]),
[#text(size: 8pt)[HEK]], [#text(size: 8pt)[Sage]], [#text(size: 8pt)[6]], [#text(size: 8pt)[17.32]], [#text(size: 8pt)[3842.9]],
[#text(size: 8pt)[HEK]], [#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[6]], [#text(size: 8pt)[20.41]], [#text(size: 8pt)[2816.7]],
[#text(size: 8pt)[Mixture]], [#text(size: 8pt)[Sage]], [#text(size: 8pt)[6]], [#text(size: 8pt)[39.23]], [#text(size: 8pt)[5346.2]],
[#text(size: 8pt)[Mixture]], [#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[6]], [#text(size: 8pt)[42.65]], [#text(size: 8pt)[4333.8]],
)
