// AUTO-GENERATED by gen_scientific_table.py, do not edit by hand.
#table(columns: 5, inset: 5pt, align: left,
table.header([#text(size: 8pt)[Workload]], [#text(size: 8pt)[Engine]], [#text(size: 8pt)[Seconds]], [#text(size: 8pt)[Peak MiB]], [#text(size: 8pt)[Target PSMs]]),
[#text(size: 8pt)[standard]], [#text(size: 8pt)[Sage]], [#text(size: 8pt)[5.50]], [#text(size: 8pt)[1911.6]], [#text(size: 8pt)[2214]],
[#text(size: 8pt)[standard]], [#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[6.69]], [#text(size: 8pt)[1238.7]], [#text(size: 8pt)[2214]],
[#text(size: 8pt)[common-mods]], [#text(size: 8pt)[Sage]], [#text(size: 8pt)[11.30]], [#text(size: 8pt)[5406.3]], [#text(size: 8pt)[2266]],
[#text(size: 8pt)[common-mods]], [#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[14.05]], [#text(size: 8pt)[3002.9]], [#text(size: 8pt)[2357]],
)
