// AUTO-GENERATED by gen_scientific_table.py, do not edit by hand.
#table(columns: 5, inset: 5pt, align: left,
table.header([#text(size: 8pt)[Study]], [#text(size: 8pt)[Engine]], [#text(size: 8pt)[Searches]], [#text(size: 8pt)[Median seconds]], [#text(size: 8pt)[Median peak MiB]]),
[#text(size: 8pt)[HEK]], [#text(size: 8pt)[Sage]], [#text(size: 8pt)[6]], [#text(size: 8pt)[19.59]], [#text(size: 8pt)[3883.7]],
[#text(size: 8pt)[HEK]], [#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[6]], [#text(size: 8pt)[22.88]], [#text(size: 8pt)[3144.6]],
[#text(size: 8pt)[Mixture]], [#text(size: 8pt)[Sage]], [#text(size: 8pt)[6]], [#text(size: 8pt)[45.03]], [#text(size: 8pt)[5456.0]],
[#text(size: 8pt)[Mixture]], [#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[6]], [#text(size: 8pt)[51.53]], [#text(size: 8pt)[4362.4]],
)
