// AUTO-GENERATED by gen_scientific_table.py, do not edit by hand.
#table(columns: 5, inset: 5pt, align: left,
table.header([#text(size: 8pt)[Workload]], [#text(size: 8pt)[Engine]], [#text(size: 8pt)[Seconds]], [#text(size: 8pt)[Peak MiB]], [#text(size: 8pt)[Target PSMs]]),
[#text(size: 8pt)[standard]], [#text(size: 8pt)[Sage]], [#text(size: 8pt)[5.71]], [#text(size: 8pt)[1903.9]], [#text(size: 8pt)[2214]],
[#text(size: 8pt)[standard]], [#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[6.41]], [#text(size: 8pt)[1502.6]], [#text(size: 8pt)[2203]],
[#text(size: 8pt)[common-mods]], [#text(size: 8pt)[Sage]], [#text(size: 8pt)[12.47]], [#text(size: 8pt)[5348.5]], [#text(size: 8pt)[2266]],
[#text(size: 8pt)[common-mods]], [#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[15.06]], [#text(size: 8pt)[3633.5]], [#text(size: 8pt)[2270]],
)
