// AUTO-GENERATED by gen_scientific_table.py, do not edit by hand.
#table(columns: 5, inset: 5pt, align: left,
table.header([#text(size: 8pt)[Study]], [#text(size: 8pt)[Engine]], [#text(size: 8pt)[Seconds (range)]], [#text(size: 8pt)[Peak MiB]], [#text(size: 8pt)[Target PSMs]]),
[#text(size: 8pt)[PXD001468]], [#text(size: 8pt)[Sage]], [#text(size: 8pt)[9.91 (9.91–9.94)]], [#text(size: 8pt)[2134.1]], [#text(size: 8pt)[16,866]],
[#text(size: 8pt)[PXD001468]], [#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[9.48 (9.43–9.50)]], [#text(size: 8pt)[1491.8]], [#text(size: 8pt)[16,917]],
[#text(size: 8pt)[PXD028735]], [#text(size: 8pt)[Sage]], [#text(size: 8pt)[26.05 (25.80–26.79)]], [#text(size: 8pt)[3071.8]], [#text(size: 8pt)[55,457]],
[#text(size: 8pt)[PXD028735]], [#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[25.03 (24.95–25.38)]], [#text(size: 8pt)[2419.9]], [#text(size: 8pt)[55,612]],
)
