// AUTO-GENERATED by gen_scientific_table.py, do not edit by hand.
#table(columns: 5, inset: 5pt, align: left,
table.header([#text(size: 8pt)[Input pair]], [#text(size: 8pt)[Shared PSMs]], [#text(size: 8pt)[Sage only]], [#text(size: 8pt)[Plus only]], [#text(size: 8pt)[Jaccard]]),
[#text(size: 8pt)[PXD001468-0]], [#text(size: 8pt)[16752]], [#text(size: 8pt)[114]], [#text(size: 8pt)[165]], [#text(size: 8pt)[0.9836]],
[#text(size: 8pt)[PXD001468-1]], [#text(size: 8pt)[19291]], [#text(size: 8pt)[115]], [#text(size: 8pt)[180]], [#text(size: 8pt)[0.9849]],
[#text(size: 8pt)[PXD028735-0]], [#text(size: 8pt)[54639]], [#text(size: 8pt)[818]], [#text(size: 8pt)[973]], [#text(size: 8pt)[0.9683]],
[#text(size: 8pt)[PXD028735-1]], [#text(size: 8pt)[55090]], [#text(size: 8pt)[850]], [#text(size: 8pt)[954]], [#text(size: 8pt)[0.9683]],
[#text(size: 8pt)[PXD028735-2]], [#text(size: 8pt)[57416]], [#text(size: 8pt)[921]], [#text(size: 8pt)[1092]], [#text(size: 8pt)[0.9661]],
[#text(size: 8pt)[PXD028735-3]], [#text(size: 8pt)[56282]], [#text(size: 8pt)[892]], [#text(size: 8pt)[1039]], [#text(size: 8pt)[0.9668]],
)
