// AUTO-GENERATED by gen_scientific_table.py, do not edit by hand.
#table(columns: 6, inset: 5pt, align: left,
table.header([#text(size: 8pt)[Study]], [#text(size: 8pt)[Engine]], [#text(size: 8pt)[Completed trials]], [#text(size: 8pt)[Seconds (range)]], [#text(size: 8pt)[Peak MiB]], [#text(size: 8pt)[Target PSMs]]),
[#text(size: 8pt)[PXD001468]], [#text(size: 8pt)[Sage]], [#text(size: 8pt)[2/3]], [#text(size: 8pt)[11.02 (10.62–11.43)]], [#text(size: 8pt)[2112.4]], [#text(size: 8pt)[16,866.0]],
[#text(size: 8pt)[PXD001468]], [#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[2/3]], [#text(size: 8pt)[10.63 (10.49–10.78)]], [#text(size: 8pt)[1497.7]], [#text(size: 8pt)[16,917.0]],
[#text(size: 8pt)[PXD028735]], [#text(size: 8pt)[Sage]], [#text(size: 8pt)[3/3]], [#text(size: 8pt)[30.17 (29.07–30.99)]], [#text(size: 8pt)[3059.8]], [#text(size: 8pt)[55,457]],
[#text(size: 8pt)[PXD028735]], [#text(size: 8pt)[Sage Plus]], [#text(size: 8pt)[3/3]], [#text(size: 8pt)[27.51 (27.05–27.72)]], [#text(size: 8pt)[2418.2]], [#text(size: 8pt)[55,612]],
)
