// AUTO-GENERATED by gen_scientific_table.py, do not edit by hand.
#table(columns: 5, inset: 5pt, align: left,
table.header([#text(size: 8pt)[Input pair]], [#text(size: 8pt)[Shared PSMs]], [#text(size: 8pt)[Sage only]], [#text(size: 8pt)[Plus only]], [#text(size: 8pt)[Jaccard]]),
[#text(size: 8pt)[PXD001468-0]], [#text(size: 8pt)[16758]], [#text(size: 8pt)[108]], [#text(size: 8pt)[255]], [#text(size: 8pt)[0.9788]],
[#text(size: 8pt)[PXD001468-1]], [#text(size: 8pt)[19284]], [#text(size: 8pt)[122]], [#text(size: 8pt)[306]], [#text(size: 8pt)[0.9783]],
[#text(size: 8pt)[PXD028735-0]], [#text(size: 8pt)[54675]], [#text(size: 8pt)[782]], [#text(size: 8pt)[1382]], [#text(size: 8pt)[0.9619]],
[#text(size: 8pt)[PXD028735-1]], [#text(size: 8pt)[55172]], [#text(size: 8pt)[776]], [#text(size: 8pt)[1445]], [#text(size: 8pt)[0.9613]],
[#text(size: 8pt)[PXD028735-2]], [#text(size: 8pt)[57458]], [#text(size: 8pt)[879]], [#text(size: 8pt)[1519]], [#text(size: 8pt)[0.9599]],
[#text(size: 8pt)[PXD028735-3]], [#text(size: 8pt)[56363]], [#text(size: 8pt)[811]], [#text(size: 8pt)[1479]], [#text(size: 8pt)[0.9610]],
)
