#!/usr/bin/env python3
"""Write the prefilter threshold sweep table for the ten-times catalog subset."""
from __future__ import annotations

from pathlib import Path

from _assets import record
from _large_db import LARGE_DB_INPUTS, completed, load

HERE = Path(__file__).resolve().parent
PAPER = HERE.parent.parent
OUT = PAPER / "si" / "prefilter_sweep_table.typ"
HEADER = f"// AUTO-GENERATED by scripts/{Path(__file__).name} -- do not edit by hand.\n"


def cell(text: str, *, bold: bool = False) -> str:
    for ch in ("\\", "[", "]", "#", "$", "*", "_", "@", "<", ">"):
        text = text.replace(ch, "\\" + ch)
    weight = ', weight: "bold"' if bold else ""
    return f"[#text(size: 6.4pt{weight})[{text}]]"


def main() -> int:
    rows = sorted(load()["threshold_sweep"],
                  key=lambda row: (row["min_matched"], -(row["max_peaks"] or 10**9)))
    lines = [
        HEADER,
        "#table(\n",
        "  columns: 8,\n",
        "  align: (right, right, right, right, right, right, right, right),\n",
        "  inset: 2.6pt,\n",
        "  table.header(\n",
        "    " + ", ".join(cell(label, bold=True) for label in (
            "Min. matches", "Peaks", "Kept (%)", "Prefilter (s)", "Wall (s)",
            "Peak RSS (GiB)", "PSMs", "Entrapment FDP (%)",
        )) + ",\n",
        "  ),\n",
    ]
    for row in rows:
        if not completed(row):
            continue
        counts = row["prefilter_counts"]
        values = (
            str(row["min_matched"]),
            "all" if row["max_peaks"] is None else str(row["max_peaks"]),
            f'{100 * counts["retained"] / counts["streamed"]:.1f}',
            f'{counts["seconds"]:.1f}',
            f'{row["wall_seconds"]:.1f}',
            f'{row["peak_rss_gib"]:.2f}',
            f'{row["accepted_psms"]:,}',
            f'{row["combined_fdp"]:.2f}',
        )
        lines.append("    " + ", ".join(cell(value) for value in values) + ",\n")
    lines.append(")\n")
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("".join(lines))
    record(
        "tbl.prefilter-sweep",
        str(OUT.relative_to(PAPER)),
        kind="table",
        inputs=LARGE_DB_INPUTS,
        desc="Prefilter match threshold and peak cap on the ten-times catalog subset.",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
