"""Write a compact table of yield at the common estimated FDP ceiling."""
from _assets import record
from _matched_fdp import PAPER, MATCHED_INPUTS, load


def main():
    rows = []
    for study in load()["summaries"]:
        for engine, label in (("upstream", "Sage"), ("plus", "Sage Plus")):
            result = study["engines"][engine]
            rows.append([
                "HEK" if study["study"] == "human" else "Mixture", label,
                f"{result['mean_targets']:,.1f}",
                f"{100 * result['fdp_min']:.3f} to {100 * result['fdp_max']:.3f}",
                f"{100 * result['q_min']:.3f} to {100 * result['q_max']:.3f}",
            ])
    headers = ["Study", "Engine", "Mean target peptides", "FDP range (%)", "q-value range (%)"]
    cell = lambda text: f"[#text(size: 8pt)[{text}]]"
    lines = ["// AUTO-GENERATED by gen_matched_fdp_table.py, do not edit by hand.\n",
             "#table(columns: 5, inset: 4pt, align: left,\n",
             "table.header(" + ", ".join(map(cell, headers)) + "),\n"]
    lines.extend(", ".join(map(cell, row)) + ",\n" for row in rows)
    output = PAPER / "si/matched_fdp.typ"
    output.write_text("".join(lines) + ")\n")
    record("tbl.matched-fdp", str(output.relative_to(PAPER)), kind="table",
           inputs=MATCHED_INPUTS, desc="Target peptide yield at a common estimated one-percent paired FDP ceiling")


if __name__ == "__main__":
    main()
