"""Generate detailed comparison tables for the expanded report."""
from statistics import median
from _assets import record
from _scientific import PAPER, INPUTS, ENGINE, load
from _report import REPORT_INPUTS, report


def cell(value):
    value=str(value)
    for char in ('\\','[',']','#','$','*','_','@','<','>'):
        value=value.replace(char,'\\'+char)
    return f'[#text(size: 8pt)[{value}]]'


def table(name,headers,rows):
    out=PAPER/'si'/f'report_{name}.typ'
    lines=['// AUTO-GENERATED by gen_report_table.py, do not edit by hand.\n',f'#table(columns: {len(headers)}, inset: 4pt, align: left,\n','table.header('+', '.join(cell(x) for x in headers)+'),\n']
    for row in rows:
        assert len(row)==len(headers)
        lines.append(', '.join(cell(x) for x in row)+',\n')
    out.write_text(''.join(lines)+')\n')
    record(f'tbl.report-{name}',str(out.relative_to(PAPER)),kind='table',inputs=INPUTS+REPORT_INPUTS,desc=f'Expanded latest-release report {name}')


def fmt(x,spec='.3f'):
    return 'undefined' if x is None else format(x,spec)


def main():
    quant=report('lfq')
    rows=[]
    for r in quant['engines']:
        for sp in ('human','yeast','ecoli'):
            m=r['species'][sp]
            rows.append([ENGINE[r['engine']],sp,fmt(m['ratio_pairs'],','),fmt(m['median_log2_bias'],'+.3f'),fmt(m['median_absolute_log2_error']),fmt(100*m['median_preparation_cv'],'.1f'),fmt(100*m['missing_fraction_observed_union'],'.3f')])
    table('lfq',['Engine','Species','Ratio pairs','Bias','Abs. error','CV (%)','Missing (%)'],rows)
    table('lfq-shared',['Species','Shared pairs','Sage abs. error','Plus abs. error','Median ratio difference'],[[sp,fmt(r['pairs'],','),fmt(r['median_absolute_error']['upstream']),fmt(r['median_absolute_error']['plus']),fmt(r['median_absolute_ratio_difference'])] for sp,r in quant['shared_ratio_pairs'].items()])
    table('control',['Engine','Control rows','Foreign','No direct MS2','Foreign, no direct MS2'],[[ENGINE[r['engine']]]+[fmt(r['control'][k],',') for k in ('quantified','foreign','without_strict_ms2','foreign_without_strict_ms2')] for r in quant['engines']])
    table('public-counts',['Input','Engine','PSMs','Peptidoforms','Decoy PSMs'],[[r['pair'].split('/')[-1],ENGINE[e]]+[fmt(r['engines'][e]['0.01'][k],',') for k in ('target_psms','target_peptidoforms','decoy_psms')] for r in report('public') for e in ('upstream','plus')])
    rows=[]
    scale=report('scaling')
    for t in (1,2,4,8):
        for e in ('upstream','plus'):
            g=[r for r in scale if r['engine']==e and r['threads']==t and not r['warmup']]
            rows.append([ENGINE[e],t,len(g),fmt(median(r['seconds'] for r in g),'.2f'),f"{min(r['seconds'] for r in g):.2f} to {max(r['seconds'] for r in g):.2f}",fmt(median(r['rss'] for r in g),'.1f'),(f"{g[0]['target_psms']:,}" if len({r['target_psms'] for r in g}) == 1 else f"{min(r['target_psms'] for r in g):,} to {max(r['target_psms'] for r in g):,}")])
    table('scaling',['Engine','Workers','Completed trials','Seconds','Time range','Peak MiB','PSM range'],rows)
    pilot,_=load()
    table('ptm-diagnostic',['HCD input','Consistent sites','Inconsistent sites','Inconsistent (%)','Jointly accepted sites'],[[r['job'].split('-')[1],r['correct_site_events'],r['incorrect_site_events'],fmt(100*r['empirical_site_error_fraction'],'.2f'),r['joint_psm_peptide_localization_1pct']['correct_site_events']+r['joint_psm_peptide_localization_1pct']['incorrect_site_events']] for r in pilot['ptm'] if r['suite']=='ptm' and r['job'].endswith('-all')])


if __name__ == '__main__':
    main()
