"""Generate the development inventory from reviewed release descriptions."""
import json
from pathlib import Path

from _assets import record

PAPER = Path(__file__).resolve().parents[2]
SRC = PAPER / 'analysis/data/development-changes.json'
OUT = PAPER / 'si/development.typ'


def cell(value):
    for char in ('\\', '[', ']', '#', '$', '*', '_', '@', '<', '>'):
        value = value.replace(char, '\\' + char)
    return f'[#text(size: 8pt)[{value}]]'


def main():
    data = json.loads(SRC.read_text())
    headers = ['Area', 'Upstream Sage behavior', 'Sage Plus change',
               'Motivation', 'Expected consequence']
    lines = [
        '// AUTO-GENERATED by gen_development_table.py, do not edit by hand.\n',
        '#set par(justify: false)\n',
        '#table(columns: (0.7fr, 1.1fr, 1.3fr, 1fr, 1fr), inset: 4pt, align: left,\n',
        'table.header(' + ', '.join(cell(x) for x in headers) + '),\n',
    ]
    for row in data['changes']:
        lines.append(', '.join(cell(row[key]) for key in
                     ('area', 'upstream', 'plus', 'motivation', 'expected')) + ',\n')
    OUT.write_text(''.join(lines) + ')\n')
    record('tbl.development', str(OUT.relative_to(PAPER)), kind='table',
           inputs=[str(SRC.relative_to(PAPER))],
           desc='Released Sage Plus changes, design motivations, and expected consequences')


if __name__ == '__main__':
    main()
