#!/usr/bin/env python3
"""Generate comparison tables from frozen latest-release evidence."""
from statistics import median
from _assets import record
from _scientific import ENGINE, STUDY, INPUTS, PAPER, load, timing


def cell(value):
    value = str(value)
    for char in ('\\', '[', ']', '#', '$', '*', '_', '@', '<', '>'):
        value = value.replace(char, '\\' + char)
    return f'[#text(size: 8pt)[{value}]]'


def table(name, headers, rows):
    out = PAPER / 'si' / f'scientific_{name}.typ'
    lines = ['// AUTO-GENERATED by gen_scientific_table.py, do not edit by hand.\n',
             f'#table(columns: {len(headers)}, inset: 5pt, align: left,\n',
             'table.header(' + ', '.join(cell(x) for x in headers) + '),\n']
    for row in rows:
        assert len(row) == len(headers)
        lines.append(', '.join(cell(x) for x in row) + ',\n')
    out.write_text(''.join(lines) + ')\n')
    record(f'tbl.scientific-{name}', str(out.relative_to(PAPER)), kind='table', inputs=INPUTS,
           desc=f'Frozen latest-release comparison {name}')


def fmt(value, spec='.3f'):
    return 'undefined' if value is None else format(value, spec)


def main():
    pilot, _ = load()
    table('timing', ['Study', 'Engine', 'Seconds (range)', 'Peak MiB', 'Target PSMs'],
          [[r['study'], ENGINE[r['engine']],
            f"{r['seconds']:.2f} ({r['seconds_min']:.2f}–{r['seconds_max']:.2f})",
            fmt(r['rss'], '.1f'), fmt(r['psms'], ',')] for r in timing(pilot)])
    table('entrapment', ['Study', 'Sage FDP (%)', 'Plus FDP (%)', 'Difference (pp)', 'Interval (pp)'],
          [[STUDY[r['study']], fmt(100*r['means']['upstream']), fmt(100*r['means']['plus']),
            fmt(100*(r['means']['plus']-r['means']['upstream']), '+.3f'),
            ' to '.join(fmt(100*x, '+.3f') for x in r['percentile_intervals']['paired_difference'])]
           for r in pilot['calibration_uncertainty']])
    table('overlap', ['Input pair', 'Shared PSMs', 'Sage only', 'Plus only', 'Jaccard'],
          [[r['pair'].split('/')[-1], r['shared_target_psms'], r['baseline_only'], r['candidate_only'], fmt(r['jaccard'], '.4f')]
           for r in pilot['public_identifications'] if r['status']=='complete'])
    rows = []
    for study in ('human', 'hye'):
        for engine in ('upstream', 'plus'):
            group = [r for r in pilot['jobs'] if r['suite'].startswith(f'entrapment-{study}-') and r['engine']==engine]
            assert len(group)==6 and all(r['status']=='complete' for r in group)
            rows.append([STUDY[study], ENGINE[engine], len(group), fmt(median(r['wall_seconds'] for r in group), '.2f'), fmt(median(r['peak_rss_mib'] for r in group), '.1f')])
    table('enlarged', ['Study', 'Engine', 'Searches', 'Median seconds', 'Median peak MiB'], rows)
    rows = []
    for workload in ('standard', 'common-mods'):
        for engine in ('upstream', 'plus'):
            group = [r for r in pilot['jobs'] if r['suite']=='local-paired' and r['workload']==workload and r['engine']==engine and not r['warmup']]
            assert len(group)==3 and all(r['status']=='complete' for r in group)
            rows.append([workload, ENGINE[engine], fmt(median(r['wall_seconds'] for r in group), '.2f'), fmt(median(r['peak_rss_mib'] for r in group), '.1f'), median(r['target_psms'] for r in group)])
    table('local', ['Workload', 'Engine', 'Seconds', 'Peak MiB', 'Target PSMs'], rows)
    rows = []
    for study in ('human', 'hye'):
        for engine in ('upstream', 'plus'):
            for q in (0.001, 0.005, 0.01, 0.02, 0.05):
                group = [t for r in pilot['calibration'] if r['suite'].startswith(f'entrapment-{study}-') and r['job'].endswith('-'+engine) for t in r['thresholds'] if t['nominal_q']==q]
                assert len(group)==6
                rows.append([STUDY[study], ENGINE[engine], fmt(100*q, '.1f'), fmt(sum(r['targets'] for r in group)/len(group), '.1f'), fmt(100*sum(r['paired_fdp_tie_max'] for r in group)/len(group))])
    table('thresholds', ['Study', 'Engine', 'Nominal q (%)', 'Mean targets', 'Mean paired FDP (%)'], rows)


if __name__ == '__main__':
    main()
