#!/usr/bin/env python3
"""Write a compact beta.2 change summary table from committed source data."""
from __future__ import annotations

import csv
from pathlib import Path

from _assets import record

HERE = Path(__file__).resolve().parent
SRC = HERE / "change_summary.csv"
PAPER = HERE.parent.parent
OUT = PAPER / "si" / "change_summary_table.typ"

HEADER = f"// AUTO-GENERATED by scripts/{Path(__file__).name} -- do not edit by hand.\n"


def cell(text: str, *, bold: bool = False) -> str:
    for ch in ("\\", "[", "]", "#", "$", "*", "_", "@", "<", ">"):
        text = text.replace(ch, "\\" + ch)
    weight = ', weight: "bold"' if bold else ""
    return f"[#text(size: 7.1pt{weight})[{text}]]"


def main() -> int:
    with SRC.open(newline="") as fh:
        rows = list(csv.DictReader(fh))

    lines = [
        HEADER,
        "#table(\n",
        "  columns: (20%, 42%, 38%),\n",
        "  align: (left, left, left),\n",
        "  inset: 3.5pt,\n",
        "  table.header(\n",
        "    " + ", ".join(cell(label, bold=True) for label in (
            "Area", "What changed", "Reader impact"
        )) + ",\n",
        "  ),\n",
    ]
    for row in rows:
        values = (row["area"], row["update"], row["reader impact"])
        lines.append("  " + ", ".join(cell(value) for value in values) + ",\n")
    lines.append(")\n")

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("".join(lines))
    record(
        "tbl.changes",
        str(OUT.relative_to(PAPER)),
        kind="table",
        inputs=[str(SRC.relative_to(PAPER))],
        desc="Beta.2 change areas and reader impact",
    )
    print(f"wrote {OUT.relative_to(PAPER)}  ({len(rows)} rows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
