#!/usr/bin/env python3
"""Write the large-database run table: every search, completed or refused."""
from __future__ import annotations

from pathlib import Path

from _assets import record
from _large_db import LARGE_DB_INPUTS, database_label, load, outcome

HERE = Path(__file__).resolve().parent
PAPER = HERE.parent.parent
OUT = PAPER / "si" / "large_db_table.typ"
HEADER = f"// AUTO-GENERATED by scripts/{Path(__file__).name} -- do not edit by hand.\n"
SERIES = (
    ("scaling", ""),
    ("narrow", ", monoisotopic"),
    ("six_frame", ""),
    ("metaproteome", ""),
)


def cell(text: str, *, bold: bool = False) -> str:
    for ch in ("\\", "[", "]", "#", "$", "*", "_", "@", "<", ">"):
        text = text.replace(ch, "\\" + ch)
    weight = ', weight: "bold"' if bold else ""
    return f"[#text(size: 6.4pt{weight})[{text}]]"


def number(value, fmt: str) -> str:
    return "" if value is None else format(value, fmt)


def main() -> int:
    summary = load()
    lines = [
        HEADER,
        "#table(\n",
        "  columns: 8,\n",
        "  align: (left, left, left, right, right, right, right, right),\n",
        "  inset: 2.6pt,\n",
        "  table.header(\n",
        "    " + ", ".join(cell(label, bold=True) for label in (
            "Database", "Prefilter", "Outcome", "Wall (s)", "Peak RSS (GiB)",
            "Peptides searched", "PSMs", "Peptides",
        )) + ",\n",
        "  ),\n",
    ]
    for series, suffix in SERIES:
        for row in summary.get(series, []):
            values = (
                database_label(series, row) + suffix,
                "yes" if row["prefilter"] else "no",
                outcome(row),
                number(row.get("wall_seconds"), ".1f"),
                number(row.get("peak_rss_gib"), ".2f"),
                number(row.get("database_peptides"), ","),
                number(row.get("accepted_psms"), ","),
                number(row.get("accepted_peptides"), ","),
            )
            lines.append("    " + ", ".join(cell(value) for value in values) + ",\n")
    lines.append(")\n")
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("".join(lines))
    record(
        "tbl.large-db",
        str(OUT.relative_to(PAPER)),
        kind="table",
        inputs=LARGE_DB_INPUTS,
        desc="Every large-database search with its outcome, cost, and identifications.",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
