#!/usr/bin/env python3
"""Write the mass offset cost and identification table."""
from __future__ import annotations

from pathlib import Path


from _assets import record
from _mass_offset import LABEL, MASS_OFFSET_INPUTS, load

HERE = Path(__file__).resolve().parent
PAPER = HERE.parent.parent
OUT = PAPER / "si" / "mass_offset_table.typ"
HEADER = f"// AUTO-GENERATED by scripts/{Path(__file__).name} -- do not edit by hand.\n"


def cell(text: str, *, bold: bool = False) -> str:
    for ch in ("\\", "[", "]", "#", "$", "*", "_", "@", "<", ">"):
        text = text.replace(ch, "\\" + ch)
    weight = ', weight: "bold"' if bold else ""
    return f"[#text(size: 6.7pt{weight})[{text}]]"


def main() -> int:
    summary = load()
    lines = [
        HEADER,
        "#table(\n",
        "  columns: 8,\n",
        "  align: (left, right, right, right, right, right, right, right),\n",
        "  inset: 3pt,\n",
        "  table.header(\n",
        "    " + ", ".join(cell(label, bold=True) for label in (
            "Configuration", "Search", "Wall", "Peak RSS", "DB peptides",
            "Fragments", "PSMs", "Offset PSMs",
        )) + ",\n",
        "  ),\n",
    ]
    for row in summary["scale"]:
        values = (
            LABEL[row["configuration"]],
            f'{row["search_stage_seconds"]:.1f} s',
            f'{row["wall_seconds"]:.1f} s',
            f'{row["peak_rss_mib"]:,.0f} MiB',
            f'{row["database_peptides"]:,}',
            f'{row["database_fragments"]:,}',
            f'{row["psms"]:,}',
            f'{row["offset_psms"]:,}',
        )
        lines.append("    " + ", ".join(cell(value) for value in values) + ",\n")
    lines.append(")\n")
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("".join(lines))
    record(
        "tbl.mass-offset",
        str(OUT.relative_to(PAPER)),
        kind="table",
        inputs=MASS_OFFSET_INPUTS,
        desc="Mass offset cost, index size, and accepted identifications.",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
