#!/usr/bin/env python3
"""Write the dense PTM site-library scaling table."""
from __future__ import annotations

import csv
from pathlib import Path

from _assets import record

HERE = Path(__file__).resolve().parent
SRC = HERE / "ptm_library_results.csv"
COMPARISON_SRC = HERE / "ptm_comparison_results.csv"
PAPER = HERE.parent.parent
OUT = PAPER / "si" / "ptm_library_table.typ"
HEADER = f"// AUTO-GENERATED by scripts/{Path(__file__).name} -- do not edit by hand.\n"


def cell(text: str, *, bold: bool = False) -> str:
    for ch in ("\\", "[", "]", "#", "$", "*", "_", "@", "<", ">"):
        text = text.replace(ch, "\\" + ch)
    weight = ', weight: "bold"' if bold else ""
    return f"[#text(size: 6.7pt{weight})[{text}]]"


def main() -> int:
    with SRC.open(newline="") as fh:
        library_rows = list(csv.DictReader(fh))
    with COMPARISON_SRC.open(newline="") as fh:
        comparison_rows = {row["condition"]: row for row in csv.DictReader(fh)}
    rows = [
        ("Conventional", comparison_rows["Conventional"]),
        ("Exhaustive", comparison_rows["Exhaustive"]),
        *((f'Library {int(row["library_sites"]):,}', row) for row in library_rows),
    ]
    lines = [
        HEADER,
        "#table(\n",
        "  columns: 7,\n",
        "  align: (right, right, right, right, right, right, right),\n",
        "  inset: 3pt,\n",
        "  table.header(\n",
        "    " + ", ".join(cell(label, bold=True) for label in (
            "Condition", "Wall", "Peak RSS", "DB peptides", "Fragments", "PSMs", "Peptides"
        )) + ",\n",
        "  ),\n",
    ]
    for label, row in rows:
        values = (
            label,
            f'{float(row["wall_seconds"]):.2f} s',
            f'{float(row["peak_rss_mib"]):,.1f} MiB',
            f'{int(row["database_peptides"]):,}',
            f'{int(row["database_fragments"]):,}',
            f'{int(row["psms"]):,}',
            f'{int(row["accepted_peptides"]):,}',
        )
        lines.append("    " + ", ".join(cell(value) for value in values) + ",\n")
    lines.append(")\n")
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("".join(lines))
    record(
        "tbl.ptm-library",
        str(OUT.relative_to(PAPER)),
        kind="table",
        inputs=[str(SRC.relative_to(PAPER)), str(COMPARISON_SRC.relative_to(PAPER))],
        desc="Conventional, exhaustive, and PTM site-library medians",
    )
    print(f"wrote {OUT.relative_to(PAPER)}  ({len(rows)} rows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
