"""Report every comparative search attempt, including unsuccessful runs."""
import json
from collections import defaultdict
from _assets import record
from _scientific import PAPER, ENGINE

SOURCE = PAPER / 'analysis/data/execution.json'


def main():
    data = json.loads(SOURCE.read_text())
    groups = defaultdict(list)
    for row in data['attempts']:
        groups[row['suite'], row['engine']].append(row)
    lines = ['// AUTO-GENERATED by gen_execution_table.py, do not edit by hand.\n',
             '#set par(justify: false)\n',
             '#table(columns: (2fr, 1fr, 1fr, 1fr, 1fr), inset: 4pt,\n',
             'table.header([Workload], [Engine], [Attempts], [Completed], [Failed]),\n']
    labels = {'public-timing': 'Public repeat timing', 'public-comparison-v2': 'Public identification',
              'report-threads': 'Worker scaling', 'report-lfq': 'Label-free quantification',
              'ptm': 'Synthetic phosphorylation', 'local-paired': 'Local standard and modified',
              'entrapment': 'Peptide entrapment'}
    for (suite, engine), rows in sorted(groups.items()):
        complete = sum(row['status'] == 'complete' for row in rows)
        values = [labels.get(suite, suite), ENGINE[engine], len(rows), complete, len(rows) - complete]
        lines.append(', '.join(f'[#text(size: 8pt)[{value}]]' for value in values) + ',\n')
    path = PAPER / 'si/execution.typ'
    path.write_text(''.join(lines) + ')\n')
    record('tbl.execution', str(path.relative_to(PAPER)), kind='table',
           inputs=['analysis/data/execution.json'], desc='Completed and failed comparative search attempts')


if __name__ == '__main__':
    main()
