// =============================================================================
// Manuscript skeleton. Edit config.typ for the title/authors/abstract, then
// replace the placeholder sections below with real prose.
//
// DO NOT delete the "BODY START" / "BODY END" marker comments. Three separate
// tools slice the prose out of this file at those markers -- the word counter,
// the readability report, and the audiobook narrator -- and each fails loudly
// rather than guessing if they go missing.
//
// The docx-mode machinery in this preamble is load-bearing for `just docx` and
// is inert on the PDF path. Read the comments before changing it.
// =============================================================================

#import "@preview/arkheion:0.1.0": arkheion, arkheion-appendices
#import "config.typ": *
// Numbers generated by the analysis, read as #s("id"). See stats.typ. Delete
// this import along with stats.typ, stats.json and analysis/scripts/
// gen_stats.py if the project states no computed numbers in its prose.
#import "stats.typ": lit, n, s, todo
// Generated figures and tables, referenced as #fig("id") / #tbl("id"). See
// assets.typ. Delete this import along with assets.typ and assets.json if the
// project includes no generated figures or tables.
#import "assets.typ": fig, tbl

// Word-export path (`just docx`): compiling with --input docx=true bypasses the
// arkheion template. Its front matter and heading styling are built from layout-only
// primitives (page/pad/line/block) that Typst's HTML export discards, which silently
// drops every section heading and the abstract. In docx mode we skip the template and
// emit plain front matter instead, so headings survive as real <h2>/<h3> elements.
// With the flag absent this is inert and the PDF is byte-for-byte unchanged.
#let docx-mode = sys.inputs.at("docx", default: "") == "true"

#let _template = arkheion.with(
  title: paper-title,
  authors: paper-authors,
  abstract: paper-abstract,
  keywords: paper-keywords,
  date: paper-date,
)

// Apply the template for PDF. In docx mode pass the document through untouched.
#show: if docx-mode { doc => doc } else { _template }

// arkheion normally supplies heading numbering. Without it the `@sec:` cross-references
// fail to resolve, so restore it on the docx path only. The SI's own "S1"-style
// numbering is set later in the file and still overrides this for the appendix.
#set heading(numbering: "1.") if docx-mode

// Typst's HTML export drops equations outright, which would gut any sentence built
// around inline math. html.frame keeps each one as an SVG that typst2docx.py then
// rasterizes back inline. Identity on the PDF path, so print output is unchanged.
#show math.equation: it => if docx-mode { html.frame(it) } else { it }

// Front matter for the Word/HTML path only (the template would normally supply it).
// The author line comes from config.typ, built from the same author list the PDF
// template uses, so the superscript affiliation markers cannot drift.
#if docx-mode {
  text(17pt, weight: "bold", paper-title)
  parbreak()
  text(11pt, paper-author-line)
  parbreak()
  for (i, affil) in paper-affiliations.enumerate() {
    text(9pt, style: "italic", super(str(i + 1)) + " " + affil)
    linebreak()
  }
  parbreak()
  text(10pt, strong("Abstract.") + " " + paper-abstract)
  parbreak()
  text(9pt, strong("Keywords: ") + paper-keywords.join(", "))
}

// Print just a cross-reference's number (e.g. "3") with no "Figure"/"Table"/
// "Section" prefix, for enumerations like "Figures 2 and 3".
#let refn(l) = ref(l, supplement: none)

// >>> BODY START -- everything from here to BODY END is counted as prose and narrated.

= Introduction and motivation

Sage is an open-source engine for peptide identification and quantification from
mass spectrometry data @lazear2023. We developed Sage Plus as an independently
maintained downstream distribution with broader input support, structured
analytical outputs, explicit memory controls, and additional quantification and
post-translational modification (PTM) functionality. Sage Plus integrates these
extensions into a single search and quantification pipeline.

We evaluated whether these changes reduce resource use while preserving
identification results and quantitative accuracy. Compact storage can reduce
memory, whereas preprocessing and predictive models can change candidate
rankings and confidence scores. We therefore compared Sage #lit(
  "v0.15.0-beta.2",
) and Sage Plus #lit("v0.1.0-beta.3") using resource measurements, accepted
peptide-spectrum match (PSM) identities, independent peptide entrapment
estimates, known mixture ratios, and a species-absent quantitative control.

= Development of Sage Plus <sec:development>

== Relationship to upstream Sage and design goals

Sage Plus retains Sage's indexed peptide search, target-decoy workflow, Git
history, authorship, MIT license, and citation metadata. Its independent version
sequence distinguishes it from upstream releases. Development focused on memory
use, additional input formats, structured output, and modification-aware
analysis. @tbl:development connects the released changes to the measurements in
this chapter. The source map is in @sec:si-development.

#figure(
  tbl("tbl.development"),
  caption: [Development areas in Sage Plus relative to Sage #lit(
      "v0.15.0-beta.2",
    ). Changes describe the evaluated Sage Plus #lit("v0.1.0-beta.3") snapshot.
    Evaluation refers to the complete released workflows. Individual mechanisms
    were not isolated by ablation.],
) <tbl:development>

== Input support and analytical output

Sage already supported mzML, Mascot Generic Format, Bruker data, and optional
Parquet output. Sage Plus added local mzMLb and direct Thermo RAW readers, as
well as pre-digested peptide input and additive protein-specific cleavage sites.
These extensions support workflows whose data or digestion assumptions are
difficult to express through the original input paths. Local seekable-file
requirements remain part of the new reader interfaces. The matched searches in
this chapter used common converted inputs, so they assess downstream behavior
without isolating the fidelity or performance of each added reader.

Parquet became the canonical analytical representation in Sage Plus. Typed
protein occurrences preserve sequence coordinates and flanking residues in PSM
output. Label-free quantification (LFQ) output uses one precursor and file per
row, with missing integrated signals represented as nulls. This representation
supports typed queries and explicit joins between search, quantification, and
site results. Existing scripts must adapt to the changed schema. The evaluation
therefore reads the underlying result tables through a common normalizer before
comparing identities or intensities.

== Memory representation and execution controls

The memory work targeted structures that expand with the number of peptides,
modification variants, theoretical fragments, and loaded spectra. Target peptide
sequences can reference immutable source-protein storage by coordinates.
Generated decoys and pre-digested peptides retain owned storage. Compact
modification records share definitions across the database, and the theoretical
fragment index stores lossless six-byte records with shared mass prefixes.
Compact spectrum storage further reduces the resident representation. These
changes aim to preserve sequence and mass information while reducing repeated
allocations and per-record storage.

Representation changes can alter access costs even when they preserve stored
information. Exact database prefiltering similarly trades additional preparation
work for a smaller retained index. Because prefiltering can affect which target
and decoy candidates enter scoring, its effects cannot be evaluated from memory
use alone. We measured runtime and identification behavior alongside memory.

Memory estimation, runtime limits, minimum-free-memory protection, and
configurable batching constrain searches that could exceed workstation capacity.
The runner also exposes validation, progress, and cancellation interfaces.
Automation interfaces were not evaluated here.

== Scientific and modeling extensions

Sage Plus adds averagine-scored isotope envelopes, charge-aware fragment
matching, per-file mass-error alignment, and richer retention-time and mobility
prediction. These changes can affect candidate scores and acceptance thresholds.
The comparison evaluates their combined effects with the storage and execution
changes. Controlled ablations would be needed to attribute a result to an
individual mechanism. Implementation details are recorded in
@sec:si-development.

== Quantification and modification functionality

Structured modifications add names, per-modification occurrence limits, total
variant caps, and optional or required neutral-loss fragments. These controls
make modification identity and search-space expansion explicit. A variant cap
also changes which hypotheses are searched, so its effect belongs in the
scientific interpretation of a configured workload.

LFQ adds configurable match-between-runs tolerance and a switch for cross-run
extraction. The quantitative experiment tests unlabeled LFQ ratios, coverage,
and a species-absent control. Labeled channels and empirical library export are
additional capabilities that were not evaluated here.

PTM functionality includes localization, ambiguity-aware sequences, site
reports, and target-decoy localization q-values. The restricted synthetic
phosphorylation experiment and its acceptance criteria are described in
@sec:si-ptm.

= Evaluation design <sec:methods>

== Software and comparison design

The comparison used the released Sage and Sage Plus versions named above.
@sec:si-provenance records software versions, source commits, and the evidence
archive location.

Each matched pair used the same spectra, reference database, search settings,
and worker count. Searches ran sequentially on an Intel Core i7-10700K system
under Linux. The principal comparisons used eight Rayon workers. A common
process address-space ceiling of #lit("16") GiB bounded allocation. Sage Plus
also applied its configured #lit("10") GiB memory guard. The two controls
measure different resource limits.

The experiment compares complete executable behavior under matched inputs.
Identical configuration keys can activate different implementations, as
described in @sec:development. Default modeling behavior was retained within
each frozen executable.

== Public spectra and reference databases

The human embryonic kidney (HEK) dataset, Proteomics Identifications Database
(PRIDE) accession PXD001468, supplied two fraction acquisitions from a published
proteomics study @chick2015. Tandem mass spectra were extracted from mzXML into
Mascot Generic Format without additional centroiding. Charge, precursor,
retention time, and array lengths were checked during conversion. This
derivative contains tandem spectra for identification and cannot support an
evaluation of precursor quantification.

PRIDE accession PXD028735 supplied four Orbitrap data-dependent acquisition
files from the Alpha and Beta preparations of mixture conditions A and B
@vanpuyvelde2022. The first injection from each preparation was selected from
metadata. ThermoRawFileParser `v.2.0.0-dev` converted the vendor files to mzML
with vendor peak picking and both precursor and tandem spectra retained. Both
engines received identical converted files. Preparation labels distinguish the
Alpha and Beta preparations.

Reference proteomes came from UniProt release `2026_03`. The human search used
reviewed canonical human proteins. The mixture used human, _Saccharomyces
cerevisiae_, and _Escherichia coli_ proteins with the stated retention-time
standards. The yeast identity followed the primary methods and reagent
documentation. Reference receipts preserve the selected accessions and
downloaded contents.

Sage Plus rejected mixture reference entries containing undefined `X` residues.
All completed mixture comparisons therefore used the same amended reference,
with affected proteins removed in their entirety from both engines' search
space. Excluded accessions and amendment records appear in @sec:si-inputs.

== Search settings and identification agreement

The public search used tryptic specificity, one missed cleavage, and peptide
lengths from #lit("7") to #lit("50") residues. Carbamidomethylation of cysteine
was fixed and variable modifications were absent. Precursor and fragment
tolerances were respectively ±#lit("10") and ±#lit("20") parts per million. The
search reported one PSM per spectrum and disabled chimeric assignments. Full
settings, including isotope errors and fragment charge limits, remain in the
frozen configurations.

A common extractor read underlying Sage tabular results and Sage Plus Parquet
results. It selected target PSMs at the reported #lit("1") percent spectrum
q-value threshold. Agreement used matched spectrum and peptide identities rather
than release-specific run-summary counters. The Jaccard index is the
intersection of the accepted PSM sets divided by their union. Engine-specific
discoveries were retained separately.

== Repeated timing and memory

One metadata-selected file from each public study entered the repeat timing
experiment. Each engine received one warmup and three measured trials, with
engine order alternating across trials. Timing began after acquisition,
conversion, and the primary search matrices had finished. GNU Time recorded
whole-process wall time and maximum resident set size. Reported medians exclude
warmups. Observed minimum and maximum times describe repeat variability on this
host, not confidence intervals across biological samples.

Wall time includes database construction, reading spectra, search, modeling, and
writing output. It excludes the preceding acquisition and conversion. Peak
resident memory differs from the address-space allocation limit. The two public
studies use different input formats and workloads, so absolute timings should be
compared within each study. A separate local HEK comparison is retained in the
Supporting Information as a contextual observation because it could overlap
acquisition activity.

== Independent peptide error assessment

Entrapment searches used the human reference and the amended mixture reference,
with two selected files per study and three shared database-construction seeds.
Each constructed database was searched by both engines. FDRBench #lit("1.1.1")
supplied the paired shuffled entrapment estimator @wen2025. Sequence extraction
and digestion used the documented reference rather than a small protein subset.

The independent audit retained one actual best-discriminant PSM per peptidoform
and checked consistent peptide q-values. It reproduced target and entrapment
counts at nominal peptide q-values of #lit("0.1"), #lit("0.5"), #lit("1"), #lit(
  "2",
), and #lit("5") percent. These static-modification searches required one
peptidoform per sequence. The paired estimator was bounded across exact
target-partner score ties, and the official FDRBench value was checked against
those bounds. The conservative bound supplies the reported comparison. Empty
denominators remain undefined.

A false discovery proportion (FDP) describes a realized discovery set. False
discovery rate (FDR) concerns an expectation over repetitions of an experiment.
This chapter reports entrapment estimates as FDP.

Study summaries averaged the file-by-seed estimates. A bootstrap with #s(
  "pilot.bootstrap",
) resamples kept the engines paired and resampled files and shared construction
seeds jointly across engines. The percentile interval describes uncertainty
conditional on the selected files and construction seeds. Individual spectra and
peptides were not treated as independent experimental replicates.

== Analysis of identification differences

We distinguished acceptance differences from changes in the underlying spectrum
assignment. An engine-only accepted PSM was first looked up in the complete
rank-one output of the other engine. An identical spectrum, charge, and peptide
assignment above that engine's spectrum q-value threshold was classified as a
threshold difference. A different rank-one assignment for the same spectrum and
charge formed a separate category. The remaining category contained unmatched
spectrum and charge combinations. A different charge assignment can therefore
enter the unmatched category. These categories describe where the exported
results diverge.

Threshold-response curves used the same files at every operating point. The
relative change was the Sage Plus target count divided by the Sage target count,
minus one. We computed that change separately for spectrum matches and
peptidoforms. Curves summarize file-level changes within each study, with the
observed file range retained.

== Matched worker-scaling extension

The additional worker experiment used the previously selected first HEK input.
Each released engine ran at #lit("1"), #lit("2"), #lit("4"), and #lit("8") Rayon
workers. Every engine and worker-count combination had one warmup followed by
three measured searches. Engine order alternated across trials within a worker
count. The search configuration and memory guards matched the original
comparison.

Whole-process time and resident memory were collected with the same runner as
the original pilot. Speedup was the median one-worker time divided by the median
time at the specified worker count. It includes serial work and input/output, so
it measures application scaling rather than the parallel efficiency of the
fragment-matching kernel alone. The workstation was not isolated from its normal
background services. These measurements are reported separately from the earlier
timing experiment.



== Matched label-free quantification

The quantification extension jointly searched the four mixture acquisitions and
the human-only control from PXD028735. Both releases used the same amended
reference, search settings, batch size, and eight-worker setting. Shared LFQ
settings specified hybrid peak scoring, summed integration, a spectral-angle
cutoff of #lit("0.7"), a #lit("5") parts-per-million mass tolerance, combined
charge states, and a #lit("1") percent peptide threshold. Default cross-run
extraction behavior was retained in both releases. An engine-specific
match-between-runs toggle was not introduced into this matched comparison.

Sage's wide LFQ table was converted to one precursor and file per row. Sage
Plus's long Parquet table was normalized to the same representation. The Sage
export omits decoy quantification rows, so only target rows entered comparative
yield and ratio endpoints. Protein inference was not assumed identical between
engines. Species assignment required an unambiguous protein-species mapping.
Sequences occurring in more than one reference proteome after isoleucine/leucine
normalization were excluded from mixture ratio analysis.

Primary quantitative results used positive finite intensities at a precursor LFQ
q-value of at most #lit("1") percent. The #lit("5") percent threshold was
reported separately to expose threshold-dependent yield. For each preparation,
we computed log-base-two B/A ratios without imputation. Expected values were
#lit("0") for human, #lit("-1") for yeast, and #lit("2") for _E. coli_,
following the mixture design @vanpuyvelde2022. Bias was the median difference
from the expected ratio. Absolute error was the median absolute difference.
Preparation variability was the coefficient of variation (CV) across the Alpha
and Beta intensities within a condition.

Missingness used the union of features observed in at least one of the four
mixture files for that engine. The denominator was that feature count multiplied
by the number of mixture files. It does not include all theoretically detectable
peptides. To separate changes in selected feature sets from changes in their
intensities, we also compared ratio error on identical peptide and preparation
pairs accepted by both releases.

The human-only control supplied a species-absent diagnostic. A foreign
assignment had to map only to yeast or _E. coli_ proteins and lack an
isoleucine/leucine-equivalent occurrence in the human reference. We counted
foreign positive rows both in the complete accepted control set and among rows
without direct accepted tandem spectral evidence. Direct tandem mass
spectrometry (MS2) evidence required the same peptide in the same file at both
spectrum and peptide q-values of at most #lit("1") percent. This common rule
replaced release-specific confirmation flags.

= Computational performance <sec:results>

== Public search time and memory

Sage Plus used less peak resident memory on both repeated public workloads. For
the HEK file, median memory was #s("pilot.PXD001468.plus.rss") MiB for Sage Plus
and #s("pilot.PXD001468.upstream.rss") MiB for Sage. For the mixture file, the
corresponding values were #s("pilot.PXD028735.plus.rss") and #s(
  "pilot.PXD028735.upstream.rss",
) MiB. These are reductions of #s("pilot.PXD001468.rss_reduction") and #s(
  "pilot.PXD028735.rss_reduction",
) percent relative to Sage.

Median wall time was also lower for Sage Plus in these two workloads. HEK
searches took #s("pilot.PXD001468.plus.seconds") seconds with Sage Plus and #s(
  "pilot.PXD001468.upstream.seconds",
) seconds with Sage. Mixture searches took #s("pilot.PXD028735.plus.seconds")
and #s("pilot.PXD028735.upstream.seconds") seconds, respectively. The reductions
were #s("pilot.PXD001468.seconds_reduction") and #s(
  "pilot.PXD028735.seconds_reduction",
) percent. @fig:timing shows the measured trials and their medians. Exact
summaries and target PSM counts appear in @tbl:si-timing.



#figure(
  fig("fig.endpoint-timing", width: 100%),
  caption: [Public wall time (A) and peak resident memory (B) for the specified
    Sage and Sage Plus releases. Large circles and open squares show medians of
    three measured searches per engine and study. Small points show the
    individual trials, offset vertically for visibility. Horizontal whiskers
    span the observed minimum and maximum, not confidence intervals. Labels give
    the medians. Warmups are excluded. Exact values and accepted PSM counts
    appear in @tbl:si-timing.],
) <fig:timing>

The runtime advantage reversed with entrapment-expanded references, while Sage
Plus retained lower median peak memory (@fig:workloads). The median time changes
were #s(
  "report.hek.entrapment.seconds",
) percent for HEK and #s("report.mixture.entrapment.seconds") percent for the
mixture. Their corresponding memory changes were #s("report.hek.entrapment.rss")
and #s("report.mixture.entrapment.rss") percent. These summaries span different
files and construction seeds rather than repeated searches of one input
(@fig:si-enlarged). The local conventional and common-modification searches also
favored Sage on runtime (@fig:si-local), reinforcing the dependence on workload.

#figure(
  fig("fig.report-workloads", width: 100%),
  caption: [Within-workload Sage Plus to Sage ratios for wall time (A) and peak
    resident memory (B). Values below one favor Sage Plus. Circles summarize
    repeated searches of a fixed public input. Diamonds summarize different
    files and database-construction seeds. Connecting segments are visual
    references to equality, not uncertainty intervals. Local workloads with less
    controlled timing appear only in @fig:si-local.],
) <fig:workloads>

== Worker scaling

Both releases benefited from additional workers on the selected HEK workload.
The observed one-to-eight-worker speedups were #s(
  "report.scaling.upstream.speedup",
) for Sage and #s("report.scaling.plus.speedup") for Sage Plus. Their
eight-worker median times in this extension were #s(
  "report.scaling.upstream.eight_seconds",
) and #s("report.scaling.plus.eight_seconds") seconds, respectively.
@fig:scaling shows the full response and individual measured repeats.

Sage Plus peak memory remained relatively flat as worker count increased,
whereas Sage memory increased substantially. Concurrent-search throughput was
not measured.

#figure(
  fig("fig.report-scaling", width: 100%),
  caption: [Matched worker scaling for the frozen release pair on the first HEK
    input. Panels show wall time (A), peak resident memory (B), and speedup
    relative to each engine's one-worker median (C). Lines join medians of three
    measured searches after one warmup per engine and worker count. Small points
    show individual measured searches. Worker counts are spaced by doubling.
    Warmups are excluded. Engine order alternated within each worker count.],
) <fig:scaling>

= Identification behavior and error assessment

== Agreement of accepted identifications

The completed public comparison contained #s("pilot.public_pairs") matched file
pairs. PSM Jaccard indices ranged from #s("pilot.overlap.min") to #s(
  "pilot.overlap.max",
). Both engines reported discoveries absent from the other, despite the high
overlap. @fig:overlap compares shared fractions and engine-specific counts for
every completed pair. Exact shared counts appear in @tbl:si-overlap.

#figure(
  fig("fig.endpoint-agreement", width: 100%),
  caption: [Accepted target PSM agreement at each engine's reported one-percent
    spectrum q-value threshold. Panel A partitions the union into shared and
    engine-only identities. The labeled shared fraction is the Jaccard index,
    expressed as a percentage. Panel B expands the engine-only counts so that
    small differences remain visible. HEK rows follow the frozen input order,
    and mixture rows name the condition and preparation in @sec:si-inputs.
    Mixture comparisons use the amended reference for both engines.
    @tbl:si-overlap retains the exact counts.],
) <fig:overlap>

Sage Plus reported slightly more accepted PSMs and peptidoforms in every public
file at the primary threshold. Across the HEK files, the per-file PSM changes
ranged from #s("report.PXD001468.target_psms.min") to #s(
  "report.PXD001468.target_psms.max",
) percent. Across the mixture files, they ranged from #s(
  "report.PXD028735.target_psms.min",
) to #s("report.PXD028735.target_psms.max") percent. The corresponding
peptidoform changes were #s("report.PXD001468.target_peptidoforms.min") to #s(
  "report.PXD001468.target_peptidoforms.max",
) percent for HEK and #s("report.PXD028735.target_peptidoforms.min") to #s(
  "report.PXD028735.target_peptidoforms.max",
) percent for the mixture.

The threshold-response curves in @fig:si-identification show that relative yield
depends on the nominal q-value threshold. Absolute counts for both
identification levels are retained in @fig:si-public-counts.

The disagreement analysis showed that an accepted PSM unique to one engine was
not always a different peptide assignment. Among Sage-only accepted PSMs, #s(
  "report.upstream.threshold_disagreement",
) percent had the identical assignment in Sage Plus above its acceptance
threshold. The reciprocal fraction among Sage Plus-only PSMs was #s(
  "report.plus.threshold_disagreement",
) percent. @fig:disagreement separates these threshold crossings from changed
rank-one assignments and unmatched spectrum-charge combinations.

Similar total yields can therefore conceal both changed assignments and
threshold crossings. Neither category alone establishes which engine's accepted
assignment is correct.

#figure(
  fig("fig.report-disagreement", width: 100%),
  caption: [Origin of accepted PSM disagreement at the one-percent spectrum
    threshold. Sage-only assignments appear in A and Sage Plus-only assignments
    in B. Categories indicate an identical assignment above threshold in the
    other engine, a different rank-one assignment at matched spectrum and
    charge, or no matching rank-one spectrum and charge. The last category
    includes possible charge changes. Bars show proportions within each file's
    engine-only accepted PSM set, with total counts labeled at right. No
    category establishes which peptide assignment is correct.],
) <fig:disagreement>

Acceptance depends on each engine's score distribution and estimated q-values.
The next analysis examines the independently estimated error behavior of the
peptide discovery sets.

== Peptide entrapment estimates

At the nominal #lit("1") percent peptide q-value threshold, mean paired FDP for
the HEK study was #s("pilot.human.upstream.fdp") percent for Sage and #s(
  "pilot.human.plus.fdp",
) percent for Sage Plus. For the mixture study, the estimates were #s(
  "pilot.hye.upstream.fdp",
) and #s("pilot.hye.plus.fdp") percent, respectively. The engines therefore gave
similar mean estimates in this selected pilot, with the direction of the
difference varying by study.

The Sage Plus minus Sage difference was #s("pilot.human.delta") percentage
points for HEK, with a descriptive interval from #s("pilot.human.lower") to #s(
  "pilot.human.upper",
). For the mixture, it was #s("pilot.hye.delta") percentage points, with an
interval from #s("pilot.hye.lower") to #s("pilot.hye.upper"). Both intervals
include zero, leaving the direction of the difference unresolved in this pilot.
@fig:entrapment summarizes these differences and their conditional intervals.

#figure(
  fig("fig.scientific-entrapment-pilot", width: 85%),
  caption: [Sage Plus minus Sage paired FDP at the nominal one-percent peptide
    q-value threshold. Points show study means and horizontal bars show
    conditional bootstrap percentile intervals across selected files and shared
    construction seeds. Both intervals include zero. FDP differences are in
    percentage points. These intervals do not establish equivalence or general
    FDR calibration.],
) <fig:entrapment>


Threshold calibration curves, file-by-seed differences, target counts, and mean
FDP estimates appear in @fig:si-entrapment and @fig:si-threshold-yield. They
expose the dependence on the chosen operating point. Reference coverage,
entrapment construction, and the relationship between target and entrapment
peptides remain assumptions of the estimator @wen2025.

An exploratory analysis of all observed peptide q-value steps compared target
peptide yield at a common independently estimated FDP ceiling. At or below #lit(
  "1",
) percent conservative paired FDP, the mean paired Sage Plus yield changes for
HEK and the mixture were #s("matched.human.change") and #s("matched.hye.change")
percent, respectively. These small changes indicate similar observed yields near
the common error estimate. Threshold selection and FDP estimation reused the
same entrapment observations, so this analysis does not establish a sensitivity
advantage at controlled true error (@sec:si-matched-fdp).

= Downstream analytical behavior



== Matched quantitative accuracy and coverage

The matched LFQ extension completed in both releases. At the primary precursor
threshold, Sage retained #s("report.lfq.upstream.target_precursors") target
precursors and Sage Plus retained #s("report.lfq.plus.target_precursors"). Their
positive target precursor-file counts were #s(
  "report.lfq.upstream.positive_target_file_rows",
) and #s("report.lfq.plus.positive_target_file_rows"), respectively. These
counts span the jointly searched mixture and control files. They are not protein
counts or counts of independently confirmed recipient-file transfers. Sage Plus
precursor yield changed by #s("report.lfq.yield_change.0.01") percent at the
primary threshold and by #s("report.lfq.yield_change.0.05") percent at the
secondary threshold. The direction therefore depended on the confidence cutoff.

@fig:lfq displays the species-specific ratio distributions. @fig:lfq-endpoints
compares bias, absolute ratio error, preparation CVs, and missingness. Each
ratio uses a matched preparation pair with positive intensity in both
conditions. The expected species shifts provide a stronger quantitative check
than a correlation between engine intensities alone. A high correlation could
persist despite a common ratio bias or many incorrect transfers.

Human log-ratio biases were #s("report.lfq.upstream.human.bias") for Sage and
#s("report.lfq.plus.human.bias") for Sage Plus. Yeast biases were #s(
  "report.lfq.upstream.yeast.bias",
) and #s("report.lfq.plus.yeast.bias"), while _E. coli_ biases were #s(
  "report.lfq.upstream.ecoli.bias",
) and #s("report.lfq.plus.ecoli.bias"). @tbl:si-lfq records the ratio
denominators and error summaries for each species. The histograms expose the
distribution around those summaries rather than treating a median as a complete
accuracy result.

#figure(
  fig("fig.report-lfq", width: 100%),
  caption: [Matched LFQ performance at one-percent precursor q-value. Panels A
    through C show per-preparation log-base-two B/A ratios for human, yeast, and
    E. coli. Vertical dotted lines mark the expected ratios. All panels use the
    same vertical scale. Histograms use equal-width bins normalized by each
    engine's full ratio count, with tails outside the displayed interval omitted
    visually. No intensity was imputed. Features with cross-species
    isoleucine/leucine ambiguity were excluded.],
) <fig:lfq>

#figure(
  fig("fig.endpoint-lfq", width: 100%),
  caption: [Species-level quantitative endpoints at the primary precursor
    threshold. Circles show Sage and open squares show Sage Plus, offset
    vertically within species for visibility. Panels compare median log-ratio
    bias (A), median absolute log-ratio error (B), median preparation CV (C),
    and missingness (D). The dotted line in A marks zero bias. CV describes
    Alpha versus Beta preparation variability within condition. Missingness uses
    each engine's observed union, not the theoretical proteome. Markers
    summarize engine-specific accepted sets and are not confidence intervals.
    Ratio denominators and exact values appear in @tbl:si-lfq.],
) <fig:lfq-endpoints>

The engines' accepted quantitative sets need not contain the same precursors.
The shared-set analysis retained #s("report.lfq.shared.human") human, #s(
  "report.lfq.shared.yeast",
) yeast, and #s("report.lfq.shared.ecoli") _E. coli_ peptide-preparation ratio
pairs. @fig:si-lfq-shared compares absolute error on these identical pairs. This
check separates intensity agreement on common features from the effect of
selecting different quantitative sets. Across species, the median absolute
difference between engine log-ratios on common pairs ranged from #s(
  "report.lfq.shared_difference.min",
) to #s("report.lfq.shared_difference.max"). This close agreement shows stable
quantitative behavior on the shared features.

== Species-absent control results

The human-only control contained accepted positive intensities assigned to
foreign species in both engines. Sage reported #s(
  "report.lfq.upstream.control.foreign",
) foreign rows among #s("report.lfq.upstream.control.quantified") assessable
quantified rows. Sage Plus reported #s("report.lfq.plus.control.foreign") among
#s("report.lfq.plus.control.quantified").

Among control rows without direct jointly accepted spectral evidence, foreign
assignments accounted for #s("report.lfq.upstream.control.foreign_percent")
percent in Sage and #s("report.lfq.plus.control.foreign_percent") percent in
Sage Plus. @fig:control compares foreign fractions in all accepted control rows
and the subset without direct MS2 support. @tbl:si-control retains the exact
numerators and denominators used for the control calculation.

#figure(
  fig("fig.report-control", width: 80%),
  caption: [Foreign-species fractions in the human-only control at the primary
    LFQ threshold. Groups compare all assessable positive precursor-file rows
    with the subset lacking direct MS2 support. Direct support requires the same
    peptide and file at both spectrum and peptide q-values of at most one
    percent. Foreign assignments map to yeast or E. coli without a
    human-reference sequence equivalent. The subsets overlap and do not
    represent independent samples.],
) <fig:control>

== Compatibility and incomplete workloads

Neither engine completed the broad modification stress workload under the
selected limits, so it provides no completed-search performance estimate.
Failure modes and resource limits are recorded in @sec:si-resource.

= Discussion <sec:discussion>

Sage Plus used less peak resident memory in every completed workload. Compact
storage is a plausible contributor, but the complete-executable comparison
cannot isolate its effect from preprocessing, modeling, or execution changes.
The enlarged entrapment databases also showed that lower memory need not imply
shorter runtime. The scaling results suggest that memory savings could help when
processing several files concurrently. Testing aggregate throughput at a fixed
worker budget would establish whether that benefit occurs in practice.

High PSM agreement and similar entrapment estimates show that the two releases
produced similar accepted identification sets and peptide-level error estimates
on the tested inputs. They do not establish identical assignments or equivalent
error rates. Some disagreements were confidence-threshold crossings, while
others changed the peptide assignment. The entrapment intervals are conditional
on the selected files and database-construction seeds, with no prespecified
equivalence margin or power analysis. Yield at matched nominal q-values should
therefore not be interpreted as yield at equal independently estimated error.
The exploratory comparison near a common estimated FDP ceiling also remains
descriptive because threshold selection reused the entrapment observations.

The LFQ comparison found nearly identical ratios on shared features, yet both
engines retained foreign-species signal in the human-only control. A precursor
confidence score shared across files does not establish confidence in each
extracted intensity. Confidence in cross-run extracted intensities needs
separate validation alongside ratio accuracy and coverage. The control cannot
detect erroneous human-to-human transfers, and contamination or reference errors
can contribute foreign signal. Its fractions are therefore diagnostics rather
than a general transfer-error rate.

The evaluation covers selected files from two public studies on one workstation.
Compute repeats and many precursor measurements do not add independent
biological studies, and the worker-scaling and LFQ extensions were post hoc.
Common converted inputs leave the native readers unevaluated, while labeled
channels, library export, and automation interfaces require separate assessment.
The released retention-time and final discriminant models reuse observations for
fitting and scoring, so held-out evaluation and controlled ablations remain
necessary. In the restricted synthetic phosphorylation experiment, no peptide
passed the one-percent peptide q-value threshold in either engine, so site-level
accuracy could not be evaluated (@sec:si-ptm).

Sage Plus reduced memory use while maintaining similar identification and LFQ
results on the tested datasets. Runtime remains workload dependent, and
quantitative transfer confidence and PTM acceptance require further validation.

// <<< BODY END



#bibliography("references.bib", title: [References], style: paper-bib-style)

// ===================== Supporting Information (appendix) =====================
// The SI is appended here as an appendix so the whole manuscript is a single
// compilation with one label namespace -- every @fig/@tbl/@sec resolves across
// the main text and the SI, and numbers can never drift out of sync.
// From this point on, figures and tables restart at S1, S2, ... and SI headings
// number S1, S2, ...  (page and line numbering stay continuous.)
#pagebreak()

#counter(figure.where(kind: image)).update(0)
#counter(figure.where(kind: table)).update(0)
#counter(heading).update(0)
#show figure.where(kind: image): set figure(numbering: n => "S" + str(n))
#show figure.where(kind: table): set figure(numbering: n => "S" + str(n))
#set heading(numbering: (..n) => "S" + n.pos().map(str).join("."))

// Same trap as any centred block: HTML export discards the align/block wrapper AND
// its contents, so on the Word path this whole title block vanishes and the main
// text runs straight into Section S1 with nothing marking the boundary. Emit it as
// plain content there -- a real heading, so it also lands in Word's navigation pane
// -- and keep the centred layout for the PDF.
#if docx-mode [
  #heading(level: 1, numbering: none, outlined: false)[Supporting Information]

  #text(13pt)[#paper-title]

  #text(10pt, style: "italic")[#si-authors]
] else [
  #align(center)[
    #text(15pt, weight: "bold")[Supporting Information]
    #v(2pt)
    #text(13pt)[#paper-title]
    #v(2pt)
    #text(10pt, style: "italic")[#si-authors]
  ]

  #v(1em)
]

#include "si-body.typ"
