// =============================================================================
// Manuscript skeleton. Edit config.typ for the title/authors/abstract, then
// replace the placeholder sections below with real prose.
//
// DO NOT delete the "BODY START" / "BODY END" marker comments. Three separate
// tools slice the prose out of this file at those markers -- the word counter,
// the readability report, and the audiobook narrator -- and each fails loudly
// rather than guessing if they go missing.
//
// The docx-mode machinery in this preamble is load-bearing for `just docx` and
// is inert on the PDF path. Read the comments before changing it.
// =============================================================================

#import "@preview/arkheion:0.1.0": arkheion, arkheion-appendices
#import "config.typ": *
// Numbers generated by the analysis, read as #s("id"). See stats.typ. Delete
// this import along with stats.typ, stats.json and analysis/scripts/
// gen_stats.py if the project states no computed numbers in its prose.
#import "stats.typ": lit, n, s, todo
// Generated figures and tables, referenced as #fig("id") / #tbl("id"). See
// assets.typ. Delete this import along with assets.typ and assets.json if the
// project includes no generated figures or tables.
#import "assets.typ": fig, tbl

// Word-export path (`just docx`): compiling with --input docx=true bypasses the
// arkheion template. Its front matter and heading styling are built from layout-only
// primitives (page/pad/line/block) that Typst's HTML export discards, which silently
// drops every section heading and the abstract. In docx mode we skip the template and
// emit plain front matter instead, so headings survive as real <h2>/<h3> elements.
// With the flag absent this is inert and the PDF is byte-for-byte unchanged.
#let docx-mode = sys.inputs.at("docx", default: "") == "true"

#let _template = arkheion.with(
  title: paper-title,
  authors: paper-authors,
  abstract: paper-abstract,
  keywords: paper-keywords,
  date: paper-date,
)

// Apply the template for PDF. In docx mode pass the document through untouched.
#show: if docx-mode { doc => doc } else { _template }

// arkheion normally supplies heading numbering. Without it the `@sec:` cross-references
// fail to resolve, so restore it on the docx path only. The SI's own "S1"-style
// numbering is set later in the file and still overrides this for the appendix.
#set heading(numbering: "1.") if docx-mode

// Typst's HTML export drops equations outright, which would gut any sentence built
// around inline math. html.frame keeps each one as an SVG that typst2docx.py then
// rasterizes back inline. Identity on the PDF path, so print output is unchanged.
#show math.equation: it => if docx-mode { html.frame(it) } else { it }

// Front matter for the Word/HTML path only (the template would normally supply it).
// The author line comes from config.typ, built from the same author list the PDF
// template uses, so the superscript affiliation markers cannot drift.
#if docx-mode {
  text(17pt, weight: "bold", paper-title)
  parbreak()
  text(11pt, paper-author-line)
  parbreak()
  for (i, affil) in paper-affiliations.enumerate() {
    text(9pt, style: "italic", super(str(i + 1)) + " " + affil)
    linebreak()
  }
  parbreak()
  text(10pt, strong("Abstract.") + " " + paper-abstract)
  parbreak()
  text(9pt, strong("Keywords: ") + paper-keywords.join(", "))
}

// Print just a cross-reference's number (e.g. "3") with no "Figure"/"Table"/
// "Section" prefix, for enumerations like "Figures 2 and 3".
#let refn(l) = ref(l, supplement: none)

// >>> BODY START -- everything from here to BODY END is counted as prose and narrated.

= Introduction and motivation

Sage is an open-source engine for peptide identification and quantification from
mass spectrometry data @lazear2023. We developed Sage Plus as an independently
maintained downstream distribution with broader input support, structured
analytical outputs, explicit memory controls, and additional quantification and
post-translational modification (PTM) functionality. Sage Plus integrates these
extensions into a single search and quantification pipeline.

We evaluated whether these changes reduce resource use while preserving
identification results and quantitative accuracy. Compact storage can reduce
memory, whereas preprocessing and predictive models can change candidate
rankings and confidence scores. We therefore compared Sage #lit(
  "v0.15.0-beta.2",
) and Sage Plus #lit("v0.1.0-beta.6") using resource measurements, accepted
peptide-spectrum match (PSM) identities, independent peptide entrapment
estimates, known mixture ratios, and a species-absent quantitative control.

= Development of Sage Plus <sec:development>

== Relationship to upstream Sage and design goals

Sage Plus retains Sage's indexed peptide search, target-decoy workflow, Git
history, authorship, MIT license, and citation metadata. Development focused on
memory use, additional input formats, structured output, and modification-aware
analysis. @tbl:development connects the released changes to the measurements in
this chapter. The source map is in @sec:si-development.

#figure(
  tbl("tbl.development"),
  caption: [Development areas in Sage Plus relative to Sage #lit(
      "v0.15.0-beta.2",
    ). Changes describe the evaluated Sage Plus #lit("v0.1.0-beta.6") snapshot.
    Evaluation refers to the complete released workflows. Individual mechanisms
    were not isolated by ablation.],
) <tbl:development>

== Input support and analytical output

Sage already supported mzML, Mascot Generic Format, Bruker data, and optional
Parquet output. Sage Plus added local mzMLb and direct Thermo RAW readers, as
well as pre-digested peptide input and additive protein-specific cleavage sites.
These extensions support workflows whose data or digestion assumptions are
difficult to express through the original input paths. Local seekable-file
requirements remain part of the new reader interfaces. The matched searches in
this chapter used common converted inputs, so they assess downstream behavior
without isolating the fidelity or performance of each added reader.

Parquet became the canonical analytical representation in Sage Plus. Typed
protein occurrences preserve sequence coordinates and flanking residues in PSM
output. Label-free quantification (LFQ) output uses one precursor and file per
row, with missing integrated signals represented as nulls. This representation
supports typed queries and explicit joins between search, quantification, and
site results. Existing scripts must adapt to the changed schema. The evaluation
therefore reads the underlying result tables through a common normalizer before
comparing identities or intensities.

== Memory representation and execution controls

The memory work targeted structures that expand with the number of peptides,
modification variants, theoretical fragments, and loaded spectra. Target peptide
sequences can reference immutable source-protein storage by coordinates.
Generated decoys and pre-digested peptides retain owned storage. Compact
modification records share definitions across the database, and the theoretical
fragment index stores lossless six-byte records with shared mass prefixes.
Compact spectrum storage further reduces the resident representation. These
changes aim to preserve sequence and mass information while reducing repeated
allocations and per-record storage.

Representation changes can alter access costs even when they preserve stored
information. Exact database prefiltering similarly trades additional preparation
work for a smaller retained index. Because prefiltering can affect which target
and decoy candidates enter scoring, its effects cannot be evaluated from memory
use alone. We measured runtime and identification behavior alongside memory.

Memory estimation, runtime limits, minimum-free-memory protection, and
configurable batching constrain searches that could exceed workstation capacity.
The runner also exposes validation, progress, and cancellation interfaces.
Automation interfaces were not evaluated here.

== Scientific and modeling extensions

Sage Plus adds averagine-scored isotope envelopes, charge-aware fragment
matching, per-file mass-error alignment, and richer retention-time and mobility
prediction. These changes can affect candidate scores and acceptance thresholds.
The comparison evaluates their combined effects with the storage and execution
changes. Controlled ablations would be needed to attribute a result to an
individual mechanism. Implementation details are recorded in
@sec:si-development.

== Named modifications and explicit attachment sites

Sage Plus defines each named modification once, with a mass, eligible sites, and
a shared occurrence limit. The site vocabulary distinguishes internal residues,
first and last peptide residues, and peptide or protein terminal groups. Residue
conditions may constrain a terminal group without changing its attachment
identity. For a peptide beginning with lysine, `first_residue:K` selects the
lysine residue, whereas `peptide_n_term:K` selects the terminal amino group.
These placements can share a mass and protein coordinate while representing
different chemical hypotheses (@fig:modification-model).

The same site matcher governs fixed modifications, indexed variable
modifications, search-time offsets, localization, and predictive features.
Occurrence limits apply across all sites belonging to a named definition.
Conflicting fixed definitions fail validation. Optional neutral-loss fragments
and total variant caps provide further control over the configured search space.
A cap changes which hypotheses are searched and therefore belongs in the
interpretation of that workload.

Attachment identity is retained in site reports and reusable PTM libraries.
Residue evidence cannot authorize an adjacent terminal-group modification.
Localization respects library-restricted sites and keeps other modifications
fixed when testing placements. Indistinguishable attachments are excluded from
reusable site evidence. Legacy symbol-keyed configurations remain readable,
while migration and preview commands expose the explicit definitions and their
eligible placements. Supporting methods describe the synthetic attachment tests
and analytical schema compatibility (@sec:si-attachments).

#figure(
  fig("fig.modification-model", width: 100%),
  caption: [Named modification placement and evidence reuse in Sage Plus. A: the
    terminal amino group and the first lysine residue are distinct attachments,
    despite sharing a peptide boundary. Numbers identify positions in the
    example peptide. One named definition shares its occurrence limit across its
    eligible sites. B: indexed and mass-offset search construct scored
    peptidoforms through different paths, then use the shared confidence and
    localization workflow. Indistinguishable attachments do not produce reusable
    PTM-library evidence. This schematic describes implementation semantics and
    does not measure localization accuracy.],
) <fig:modification-model>

== Search time mass offsets

A variable modification can be searched as a precursor and fragment mass offset
without expanding that modification into the fragment index. Candidate retrieval
uses translated precursor windows and both shifted and unshifted fragments.
Eligible placements become scored peptidoforms before confidence assessment,
quantification, and localization. At most one search-time offset is placed on a
peptide, and different offsets are never combined with each other. Configured
indexed modifications may still be present. This restriction bounds the searched
hypotheses but differs from unrestricted combinatorial expansion. @sec:offsets
evaluates the resulting memory and search-time tradeoff.

== Quantification and confidence assessment

LFQ adds configurable match-between-runs tolerance and a switch for cross-run
extraction. Typed output records strict confirmation from tandem spectra and
per-file signal diagnostics. These diagnostics include spectral agreement, trace
agreement, and retention-time displacement. Their ranking score is not a
calibrated probability that an individual transfer is correct. The quantitative
experiment tests unlabeled LFQ ratios, coverage, and a species-absent control.
Labeled channels and empirical spectral-library export remain unevaluated here.

When peptide or protein confidence modeling is underdetermined or gives a
nonfinite posterior, Sage Plus falls back to count-based target-decoy q-values.
Equal scores remain one threshold group. Localization with equally scoring best
target arrangements reports no confidence in an arbitrary winning site, while
retaining those arrangements in the localization competition population. The
synthetic phosphorylation experiment evaluates peptide acceptance and synthesis
consistency under explicit confidence thresholds (@sec:si-ptm).

= Evaluation design <sec:methods>

== Software and comparison design

The comparison used the released Sage and Sage Plus versions named above.
@sec:si-provenance records software versions, source commits, and the evidence
record locations.

Each matched pair used the same spectra, reference database, search settings,
and worker count. Searches ran sequentially on an Intel Core i7-10700K system
under Linux. The principal comparisons used eight Rayon workers. A common
process address-space ceiling of #lit("16") GiB bounded allocation. Sage Plus
also applied its configured #lit("10") GiB memory guard. The two controls
measure different resource limits.

The experiment compares complete executable behavior under matched inputs.
Identical configuration keys can activate different implementations, as
described in @sec:development. Default modeling behavior was retained within
each frozen executable.

== Public spectra and reference databases

The human embryonic kidney (HEK) dataset, Proteomics Identifications Database
(PRIDE) accession PXD001468, supplied two fraction acquisitions from a published
proteomics study @chick2015. Tandem mass spectra were extracted from mzXML into
Mascot Generic Format without additional centroiding. Charge, precursor,
retention time, and array lengths were checked during conversion. This
derivative contains tandem spectra for identification and cannot support an
evaluation of precursor quantification.

PRIDE accession PXD028735 supplied four Orbitrap data-dependent acquisition
files from the Alpha and Beta preparations of mixture conditions A and B
@vanpuyvelde2022. The first injection from each preparation was selected from
metadata. ThermoRawFileParser `v.2.0.0-dev` converted the vendor files to mzML
with vendor peak picking and both precursor and tandem spectra retained. Both
engines received identical converted files. Preparation labels distinguish the
Alpha and Beta preparations.

Reference proteomes came from UniProt release `2026_03`. The human search used
reviewed canonical human proteins. The mixture used human, _Saccharomyces
cerevisiae_, and _Escherichia coli_ proteins with the stated retention-time
standards. The yeast identity followed the primary methods and reagent
documentation. Reference receipts preserve the selected accessions and
downloaded contents.

Sage Plus rejected mixture reference entries containing undefined `X` residues.
All completed mixture comparisons therefore used the same amended reference,
with affected proteins removed in their entirety from both engines' search
space. Excluded accessions and amendment records appear in @sec:si-inputs.

== Search settings and identification agreement

The public search used tryptic specificity, one missed cleavage, and peptide
lengths from #lit("7") to #lit("50") residues. Carbamidomethylation of cysteine
was fixed and variable modifications were absent. Precursor and fragment
tolerances were respectively ±#lit("10") and ±#lit("20") parts per million. The
search reported one PSM per spectrum and disabled chimeric assignments. Full
settings, including isotope errors and fragment charge limits, remain in the
frozen configurations.

A common extractor read underlying Sage tabular results and Sage Plus Parquet
results. It selected target PSMs at the reported #lit("1") percent spectrum
q-value threshold. Agreement used matched spectrum and peptide identities rather
than release-specific run-summary counters. The Jaccard index is the
intersection of the accepted PSM sets divided by their union. Engine-specific
discoveries were retained separately.

== Repeated timing and memory

One metadata-selected file from each public study entered the repeat timing
experiment. Each engine received one warmup and three measured trials, with
engine order alternating across trials. Acquisition and conversion were complete
before the searches began. GNU Time recorded whole-process wall time and maximum
resident set size. Reported medians exclude warmups and failed attempts. All
failed attempts are retained separately, and completion counts accompany the
timing tables. Resource summaries are conditional on successful completion.
Observed minimum and maximum times describe repeat variability on this host, not
confidence intervals across biological samples.

Wall time includes database construction, reading spectra, search, modeling, and
writing output. It excludes the preceding acquisition and conversion. Peak
resident memory differs from the address-space allocation limit. The two public
studies use different input formats and workloads, so absolute timings should be
compared within each study. A separate local HEK comparison is retained in the
Supporting Information as a contextual observation because its biological input
provenance was not independently verified.

== Independent peptide error assessment

Entrapment searches used the human reference and the amended mixture reference,
with two selected files per study and three shared database-construction seeds.
Each constructed database was searched by both engines. FDRBench #lit("1.1.1")
supplied the paired shuffled entrapment estimator @wen2025. Sequence extraction
and digestion used the documented reference rather than a small protein subset.

The independent audit retained one actual best-discriminant PSM per peptidoform
and checked consistent peptide q-values. It reproduced target and entrapment
counts at nominal peptide q-values of #lit("0.1"), #lit("0.5"), #lit("1"), #lit(
  "2",
), and #lit("5") percent. These static-modification searches required one
peptidoform per sequence. The paired estimator was bounded across exact
target-partner score ties, and the official FDRBench value was checked against
those bounds. The conservative bound supplies the reported comparison. Empty
denominators remain undefined.

A false discovery proportion (FDP) describes a realized discovery set. False
discovery rate (FDR) concerns an expectation over repetitions of an experiment.
This chapter reports entrapment estimates as FDP.

Study summaries averaged the file-by-seed estimates. A bootstrap with #s(
  "pilot.bootstrap",
) resamples kept the engines paired and resampled files and shared construction
seeds jointly across engines. The percentile interval describes uncertainty
conditional on the selected files and construction seeds. Individual spectra and
peptides were not treated as independent experimental replicates.

== Analysis of identification differences

We distinguished acceptance differences from changes in the underlying spectrum
assignment. An engine-only accepted PSM was first looked up in the complete
rank-one output of the other engine. An identical spectrum, charge, and peptide
assignment above that engine's spectrum q-value threshold was classified as a
threshold difference. A different rank-one assignment for the same spectrum and
charge formed a separate category. The remaining category contained unmatched
spectrum and charge combinations. A different charge assignment can therefore
enter the unmatched category. These categories describe where the exported
results diverge.

Threshold-response curves used the same files at every operating point. The
relative change was the Sage Plus target count divided by the Sage target count,
minus one. We computed that change separately for spectrum matches and
peptidoforms. Curves summarize file-level changes within each study, with the
observed file range retained.

== Matched worker scaling

The worker experiment used the first selected HEK input. Each released engine
ran at #lit("1"), #lit("2"), #lit("4"), and #lit("8") Rayon workers. Every
engine and worker-count combination had one warmup followed by three measured
searches. Engine order alternated across trials within a worker count. The
search configuration and memory guards matched the public comparison.

Whole-process time and resident memory were collected with the same runner as
the public searches. Speedup was the median one-worker time divided by the
median time at the specified worker count. It includes serial work and
input/output, so it measures application scaling rather than the parallel
efficiency of the fragment-matching kernel alone. The workstation was not
isolated from its normal background services. These measurements form a separate
worker-count series.



== Matched label-free quantification

The quantification experiment jointly searched the four mixture acquisitions and
the human-only control from PXD028735. Both releases used the same amended
reference, search settings, batch size, and eight-worker setting. Shared LFQ
settings specified hybrid peak scoring, summed integration, a spectral-angle
cutoff of #lit("0.7"), a #lit("5") parts-per-million mass tolerance, combined
charge states, and a #lit("1") percent peptide threshold. Default cross-run
extraction behavior was retained in both releases. An engine-specific
match-between-runs toggle was not introduced into this matched comparison.

Sage's wide LFQ table was converted to one precursor and file per row. Sage
Plus's long Parquet table was normalized to the same representation. The Sage
export omits decoy quantification rows, so only target rows entered comparative
yield and ratio endpoints. Protein inference was not assumed identical between
engines. Species assignment required an unambiguous protein-species mapping.
Sequences occurring in more than one reference proteome after isoleucine/leucine
normalization were excluded from mixture ratio analysis.

Primary quantitative results used positive finite intensities at a precursor LFQ
q-value of at most #lit("1") percent. The #lit("5") percent threshold was
reported separately to expose threshold-dependent yield. For each preparation,
we computed log-base-two B/A ratios without imputation. Expected values were
#lit("0") for human, #lit("-1") for yeast, and #lit("2") for _E. coli_,
following the mixture design @vanpuyvelde2022. Bias was the median difference
from the expected ratio. Absolute error was the median absolute difference.
Preparation variability was the coefficient of variation (CV) across the Alpha
and Beta intensities within a condition.

Missingness used the union of features observed in at least one of the four
mixture files for that engine. The denominator was that feature count multiplied
by the number of mixture files. It does not include all theoretically detectable
peptides. To separate changes in selected feature sets from changes in their
intensities, we also compared ratio error on identical peptide and preparation
pairs accepted by both releases.

The human-only control supplied a species-absent diagnostic. A foreign
assignment had to map only to yeast or _E. coli_ proteins and lack an
isoleucine/leucine-equivalent occurrence in the human reference. We counted
foreign positive rows both in the complete accepted control set and among rows
without direct accepted tandem spectral evidence. Direct tandem mass
spectrometry (MS2) evidence required the same peptide in the same file at both
spectrum and peptide q-values of at most #lit("1") percent. This common rule
replaced release-specific confirmation flags.

== Modification strategy and attachment evaluation

The mass-offset experiment used the same Sage Plus executable as the engine
comparison. A selected HEK file was searched with indexed oxidation or with one,
two, and three configured offsets. Each configuration had two measured trials at
eight workers. The retained configurations specify indexed acetylation,
modification budgets, isotope-error windows, and the precursor and fragment
tolerances. The focused runs used a #lit("22") GiB process-memory guard and
required at least #lit("2") GiB available system memory. These limits differ
from the principal comparison and are recorded with every command.

Search-stage duration, whole-process wall time, resident memory, and index size
were collected separately. Configurations with additional offsets test more
modification hypotheses, so changes in accepted counts do not estimate a
sensitivity gain at a fixed search space. Synthetic phosphopeptide searches
compared indexed and offset placement, and a retained paired entrapment
reference supplied an additional peptide-level error diagnostic. These focused
experiments complement the full-reference engine comparison and do not add
independent biological studies.

Named-attachment fixtures tested discovery, guided PTM-library reuse, and
iteration with first-residue, last-residue, and terminal-group modifications.
The fixtures also tested ambiguity that must prevent reusable site evidence.
They assess consistency of the implemented semantics across search paths.
Empirical terminal-localization calibration requires separate data.

== Large search database evaluation

The large-database searches used Sage Plus #lit("v0.1.0-beta.10"), with
executable SHA-256 prefix `72f75a6c`. They kept the public search settings above
and added an explicit #lit("16") GiB memory limit with eight workers. Each
database was searched twice, once with the exact prefilter enabled and once
without it. The prefilter scans the spectra first and keeps only peptides that
could contribute a preliminary fragment match. Its retention therefore depends
on the precursor search space, and a separate arm restricted isotope errors to
the monoisotopic precursor. Outcomes were recorded as completed, refused by the
preflight estimate before building, or stopped by the runtime memory guard.

The scaling series searched one HEK file against the human reference combined
with random subsets of the Integrated Gene Catalog of the human gut microbiome
@li2014. The cleaned catalog held #s("large.catalog.proteins") proteins and #s(
  "large.catalog.residues",
) billion residues, about #s(
  "large.catalog.multiple",
) times the #s("large.human.residues") million human residues. Subsets were
sized as multiples of the human residue count. Catalog peptides are absent from
a human sample, so they served as entrapment sequences for the combined FDP
estimate @wen2025.

A six-frame search used one mixture file against the human reference with the
_E. coli_ K-12 and _S. cerevisiae_ genomes translated in all six frames. Frames
were split at stop codons, and open segments of at least seven residues became
entries. The annotated mixture reference served as its comparison. Two fecal
metaproteomes from the Critical Assessment of MetaProteome Investigation (CAMPI)
@vandenbossche2021 were searched against their sample-specific metagenome
database of #s("large.campi.proteins") proteins and #s("large.campi.residues")
million residues, combined with the human reference.

= Computational performance <sec:results>

== Execution completeness

The comparison recorded #s("execution.upstream.attempts") Sage attempts and #s(
  "execution.plus.attempts",
) Sage Plus attempts, including warmups. Sage had #s(
  "execution.upstream.failures",
) unsuccessful attempts and Sage Plus had #s("execution.plus.failures").
Completed-run summaries describe resource use conditional on completion. Every
attempt remains in the evidence records, and @tbl:execution reports outcomes by
workload. Failed searches do not contribute empty discovery sets or successful
timing measurements. Observed failures included an out-of-range sequence access
during Sage Plus database construction and abnormal process termination in Sage.
Their causes were not isolated by this evaluation.

== Public search time and memory

Sage Plus used less peak resident memory on both repeated public workloads. For
the HEK file, median memory was #s("pilot.PXD001468.plus.rss") MiB for Sage Plus
and #s("pilot.PXD001468.upstream.rss") MiB for Sage. For the mixture file, the
corresponding values were #s("pilot.PXD028735.plus.rss") and #s(
  "pilot.PXD028735.upstream.rss",
) MiB. These are reductions of #s("pilot.PXD001468.rss_reduction") and #s(
  "pilot.PXD028735.rss_reduction",
) percent relative to Sage.

Median wall time was also lower for Sage Plus in these two workloads. HEK
searches took #s("pilot.PXD001468.plus.seconds") seconds with Sage Plus and #s(
  "pilot.PXD001468.upstream.seconds",
) seconds with Sage. Mixture searches took #s("pilot.PXD028735.plus.seconds")
and #s("pilot.PXD028735.upstream.seconds") seconds, respectively. The reductions
were #s("pilot.PXD001468.seconds_reduction") and #s(
  "pilot.PXD028735.seconds_reduction",
) percent. @fig:timing shows the measured trials and their medians. Exact
summaries and target PSM counts appear in @tbl:si-timing.



#figure(
  fig("fig.endpoint-timing", width: 100%),
  caption: [Public wall time (A) and peak resident memory (B) for the specified
    Sage and Sage Plus releases. Large circles and open squares show medians of
    completed measured searches per engine and study. Small points show the
    individual trials, offset vertically for visibility. Horizontal whiskers
    span the observed minimum and maximum, not confidence intervals. Labels give
    the medians and completed sample sizes. Warmups and failures are excluded.
    Exact values and accepted PSM counts appear in @tbl:si-timing.],
) <fig:timing>

The runtime advantage reversed with entrapment-expanded references, while Sage
Plus retained lower median peak memory (@fig:workloads). The median time changes
were #s(
  "report.hek.entrapment.seconds",
) percent for HEK and #s("report.mixture.entrapment.seconds") percent for the
mixture. Their corresponding memory changes were #s("report.hek.entrapment.rss")
and #s("report.mixture.entrapment.rss") percent. These summaries span different
files and construction seeds rather than repeated searches of one input
(@fig:si-enlarged). The local conventional and common-modification searches also
favored Sage on runtime (@fig:si-local), reinforcing the dependence on workload.

#figure(
  fig("fig.report-workloads", width: 100%),
  caption: [Within-workload Sage Plus to Sage ratios for wall time (A) and peak
    resident memory (B). Values below one favor Sage Plus. Circles summarize
    repeated searches of a fixed public input. Diamonds summarize different
    files and database-construction seeds. Connecting segments are visual
    references to equality, not uncertainty intervals. Local workloads with less
    controlled timing appear only in @fig:si-local.],
) <fig:workloads>

== Worker scaling

Both releases benefited from additional workers on the selected HEK workload.
The observed one-to-eight-worker speedups were #s(
  "report.scaling.upstream.speedup",
) for Sage and #s("report.scaling.plus.speedup") for Sage Plus. Their
eight-worker median times in this extension were #s(
  "report.scaling.upstream.eight_seconds",
) and #s("report.scaling.plus.eight_seconds") seconds, respectively.
@fig:scaling shows the full response and individual measured repeats.

Sage Plus peak memory remained relatively flat as worker count increased,
whereas Sage memory increased substantially. Concurrent-search throughput was
not measured.

#figure(
  fig("fig.report-scaling", width: 100%),
  caption: [Matched worker scaling for the frozen release pair on the first HEK
    input. Panels show wall time (A), peak resident memory (B), and speedup
    relative to each engine's one-worker median (C). Lines join medians of
    completed measured searches after one warmup per engine and worker count.
    Small points show individual measured searches. Worker counts are spaced by
    doubling. Warmups are excluded. Engine order alternated within each worker
    count.],
) <fig:scaling>

= Identification behavior and error assessment

== Agreement of accepted identifications

The completed public comparison contained #s("pilot.public_pairs") matched file
pairs. PSM Jaccard indices ranged from #s("pilot.overlap.min") to #s(
  "pilot.overlap.max",
). Both engines reported discoveries absent from the other, despite the high
overlap. @fig:overlap compares shared fractions and engine-specific counts for
every completed pair. Exact shared counts appear in @tbl:si-overlap.

#figure(
  fig("fig.endpoint-agreement", width: 100%),
  caption: [Accepted target PSM agreement at each engine's reported one-percent
    spectrum q-value threshold. Panel A partitions the union into shared and
    engine-only identities. The labeled shared fraction is the Jaccard index,
    expressed as a percentage. Panel B expands the engine-only counts so that
    small differences remain visible. HEK rows follow the frozen input order,
    and mixture rows name the condition and preparation in @sec:si-inputs.
    Mixture comparisons use the amended reference for both engines.
    @tbl:si-overlap retains the exact counts.],
) <fig:overlap>

Sage Plus reported slightly more accepted PSMs and peptidoforms in every public
file at the primary threshold. Across the HEK files, the per-file PSM changes
ranged from #s("report.PXD001468.target_psms.min") to #s(
  "report.PXD001468.target_psms.max",
) percent. Across the mixture files, they ranged from #s(
  "report.PXD028735.target_psms.min",
) to #s("report.PXD028735.target_psms.max") percent. The corresponding
peptidoform changes were #s("report.PXD001468.target_peptidoforms.min") to #s(
  "report.PXD001468.target_peptidoforms.max",
) percent for HEK and #s("report.PXD028735.target_peptidoforms.min") to #s(
  "report.PXD028735.target_peptidoforms.max",
) percent for the mixture.

The threshold-response curves in @fig:si-identification show that relative yield
depends on the nominal q-value threshold. Absolute counts for both
identification levels are retained in @fig:si-public-counts.

The disagreement analysis showed that an accepted PSM unique to one engine was
not always a different peptide assignment. Among Sage-only accepted PSMs, #s(
  "report.upstream.threshold_disagreement",
) percent had the identical assignment in Sage Plus above its acceptance
threshold. The reciprocal fraction among Sage Plus-only PSMs was #s(
  "report.plus.threshold_disagreement",
) percent. @fig:disagreement separates these threshold crossings from changed
rank-one assignments and unmatched spectrum-charge combinations.

Similar total yields can therefore conceal both changed assignments and
threshold crossings. Neither category alone establishes which engine's accepted
assignment is correct.

#figure(
  fig("fig.report-disagreement", width: 100%),
  caption: [Origin of accepted PSM disagreement at the one-percent spectrum
    threshold. Sage-only assignments appear in A and Sage Plus-only assignments
    in B. Categories indicate an identical assignment above threshold in the
    other engine, a different rank-one assignment at matched spectrum and
    charge, or no matching rank-one spectrum and charge. The last category
    includes possible charge changes. Bars show proportions within each file's
    engine-only accepted PSM set, with total counts labeled at right. No
    category establishes which peptide assignment is correct.],
) <fig:disagreement>

Acceptance depends on each engine's score distribution and estimated q-values.
The next analysis examines the independently estimated error behavior of the
peptide discovery sets.

== Peptide entrapment estimates

At the nominal #lit("1") percent peptide q-value threshold, mean paired FDP for
the HEK study was #s("pilot.human.upstream.fdp") percent for Sage and #s(
  "pilot.human.plus.fdp",
) percent for Sage Plus. For the mixture study, the estimates were #s(
  "pilot.hye.upstream.fdp",
) and #s("pilot.hye.plus.fdp") percent, respectively. The engines therefore gave
similar mean estimates in this selected pilot, with the direction of the
difference varying by study.

The Sage Plus minus Sage difference was #s("pilot.human.delta") percentage
points for HEK, with a descriptive interval from #s("pilot.human.lower") to #s(
  "pilot.human.upper",
). For the mixture, it was #s("pilot.hye.delta") percentage points, with an
interval from #s("pilot.hye.lower") to #s("pilot.hye.upper"). Both intervals
include zero, leaving the direction of the difference unresolved in this pilot.
@fig:entrapment summarizes these differences and their conditional intervals.

#figure(
  fig("fig.scientific-entrapment-pilot", width: 85%),
  caption: [Sage Plus minus Sage paired FDP at the nominal one-percent peptide
    q-value threshold. Points show study means and horizontal bars show
    conditional bootstrap percentile intervals across selected files and shared
    construction seeds. Both intervals include zero. FDP differences are in
    percentage points. These intervals do not establish equivalence or general
    FDR calibration.],
) <fig:entrapment>


Threshold calibration curves, file-by-seed differences, target counts, and mean
FDP estimates appear in @fig:si-entrapment and @fig:si-threshold-yield. They
expose the dependence on the chosen operating point. Reference coverage,
entrapment construction, and the relationship between target and entrapment
peptides remain assumptions of the estimator @wen2025.

An exploratory analysis of all observed peptide q-value steps compared target
peptide yield at a common independently estimated FDP ceiling. At or below #lit(
  "1",
) percent conservative paired FDP, the mean paired Sage Plus yield changes for
HEK and the mixture were #s("matched.human.change") and #s("matched.hye.change")
percent, respectively. These small changes indicate similar observed yields near
the common error estimate. Threshold selection and FDP estimation reused the
same entrapment observations, so this analysis does not establish a sensitivity
advantage at controlled true error (@sec:si-matched-fdp).

= Downstream analytical behavior



== Matched quantitative accuracy and coverage

The matched LFQ extension completed in both releases. At the primary precursor
threshold, Sage retained #s("report.lfq.upstream.target_precursors") target
precursors and Sage Plus retained #s("report.lfq.plus.target_precursors"). Their
positive target precursor-file counts were #s(
  "report.lfq.upstream.positive_target_file_rows",
) and #s("report.lfq.plus.positive_target_file_rows"), respectively. These
counts span the jointly searched mixture and control files. They are not protein
counts or counts of independently confirmed recipient-file transfers. Sage Plus
precursor yield changed by #s("report.lfq.yield_change.0.01") percent at the
primary threshold and by #s("report.lfq.yield_change.0.05") percent at the
secondary threshold. The direction therefore depended on the confidence cutoff.

@fig:lfq displays the species-specific ratio distributions. @fig:lfq-endpoints
compares bias, absolute ratio error, preparation CVs, and missingness. Each
ratio uses a matched preparation pair with positive intensity in both
conditions. The expected species shifts provide a stronger quantitative check
than a correlation between engine intensities alone. A high correlation could
persist despite a common ratio bias or many incorrect transfers.

Human log-ratio biases were #s("report.lfq.upstream.human.bias") for Sage and
#s("report.lfq.plus.human.bias") for Sage Plus. Yeast biases were #s(
  "report.lfq.upstream.yeast.bias",
) and #s("report.lfq.plus.yeast.bias"), while _E. coli_ biases were #s(
  "report.lfq.upstream.ecoli.bias",
) and #s("report.lfq.plus.ecoli.bias"). @tbl:si-lfq records the ratio
denominators and error summaries for each species. The histograms expose the
distribution around those summaries rather than treating a median as a complete
accuracy result.

#figure(
  fig("fig.report-lfq", width: 100%),
  caption: [Matched LFQ performance at one-percent precursor q-value. Panels A
    through C show per-preparation log-base-two B/A ratios for human, yeast, and
    E. coli. Vertical dotted lines mark the expected ratios. All panels use the
    same vertical scale. Histograms use equal-width bins normalized by each
    engine's full ratio count, with tails outside the displayed interval omitted
    visually. No intensity was imputed. Features with cross-species
    isoleucine/leucine ambiguity were excluded.],
) <fig:lfq>

#figure(
  fig("fig.endpoint-lfq", width: 100%),
  caption: [Species-level quantitative endpoints at the primary precursor
    threshold. Circles show Sage and open squares show Sage Plus, offset
    vertically within species for visibility. Panels compare median log-ratio
    bias (A), median absolute log-ratio error (B), median preparation CV (C),
    and missingness (D). The dotted line in A marks zero bias. CV describes
    Alpha versus Beta preparation variability within condition. Missingness uses
    each engine's observed union, not the theoretical proteome. Markers
    summarize engine-specific accepted sets and are not confidence intervals.
    Ratio denominators and exact values appear in @tbl:si-lfq.],
) <fig:lfq-endpoints>

The engines' accepted quantitative sets need not contain the same precursors.
The shared-set analysis retained #s("report.lfq.shared.human") human, #s(
  "report.lfq.shared.yeast",
) yeast, and #s("report.lfq.shared.ecoli") _E. coli_ peptide-preparation ratio
pairs. @fig:si-lfq-shared compares absolute error on these identical pairs. This
check separates intensity agreement on common features from the effect of
selecting different quantitative sets. Across species, the median absolute
difference between engine log-ratios on common pairs ranged from #s(
  "report.lfq.shared_difference.min",
) to #s("report.lfq.shared_difference.max"). This close agreement shows stable
quantitative behavior on the shared features.

== Species-absent control results

The human-only control contained accepted positive intensities assigned to
foreign species in both engines. Sage reported #s(
  "report.lfq.upstream.control.foreign",
) foreign rows among #s("report.lfq.upstream.control.quantified") assessable
quantified rows. Sage Plus reported #s("report.lfq.plus.control.foreign") among
#s("report.lfq.plus.control.quantified").

Among control rows without direct jointly accepted spectral evidence, foreign
assignments accounted for #s("report.lfq.upstream.control.foreign_percent")
percent in Sage and #s("report.lfq.plus.control.foreign_percent") percent in
Sage Plus. @fig:control compares foreign fractions in all accepted control rows
and the subset without direct MS2 support. @tbl:si-control retains the exact
numerators and denominators used for the control calculation.

#figure(
  fig("fig.report-control", width: 80%),
  caption: [Foreign-species fractions in the human-only control at the primary
    LFQ threshold. Groups compare all assessable positive precursor-file rows
    with the subset lacking direct MS2 support. Direct support requires the same
    peptide and file at both spectrum and peptide q-values of at most one
    percent. Foreign assignments map to yeast or E. coli without a
    human-reference sequence equivalent. The subsets overlap and do not
    represent independent samples.],
) <fig:control>

= Mass offset search <sec:offsets>

Searching a modification as a mass offset moves work from the fragment index to
the search itself. Oxidation searched as an offset reduced the indexed peptides
from #s("offset.peptides.indexed") to #s("offset.peptides.offset"), a reduction
of #s("offset.peptides.reduction") percent. Median peak resident memory fell
from #s("offset.indexed.rss") to #s("offset.offsets.1.rss") MiB, a reduction of
#s("offset.rss.reduction") percent. The median search stage grew from #s(
  "offset.indexed.search",
) to #s("offset.offsets.1.search") seconds, a factor of #s(
  "offset.search.multiplier",
). Offsets are never combined with each other, so adding more of them extends
the searched hypothesis count linearly. Two offsets took #s(
  "offset.offsets.2.search",
) seconds and three took #s("offset.offsets.3.search"), an average of #s(
  "offset.search.per_offset",
) added seconds each, while the index retained the same indexed modifications
and peak memory at #s("offset.offsets.3.rss") MiB (@fig:mass-offset). Accepted
PSMs rose slightly across these configurations, from #s("offset.indexed.psms")
to #s("offset.offsets.3.psms"), because an offset is tested against every
indexed peptidoform. Exact values appear in @tbl:si-mass-offset.

#figure(
  fig("fig.mass-offset", width: 100%),
  caption: [Mass offset cost and behavior on one public HEK file. A: median
    search stage against the number of configured offsets, which are never
    combined with each other. B and C: indexed peptides and median peak resident
    memory, which follow the indexed modifications only. Bars are shaded by the
    number of offsets, with the indexed baseline in gray. D: inconsistent
    localized site events after joint spectrum, peptide, and localization
    filtering on the synthetic phosphopeptide libraries, and combined entrapment
    false-discovery proportion at one percent peptide q-value on the paired
    oxidation search. The two measures in D come from different experiments and
    share only their percent scale.],
) <fig:mass-offset>

The synthetic phosphopeptide assignments were closely concordant between the
search modes. Across #s("offset.agreement.spectra") synthetic phosphopeptide
spectra shared by both modes, #s("offset.agreement.same") received the same
rank-one peptidoform and #s("offset.agreement.differing") differed.
Synthesis-consistency diagnostics counted #s("offset.sites.indexed.correct")
consistent site events for the expanded search and #s(
  "offset.sites.offset.correct",
) for the offset search, with inconsistent fractions of #s(
  "offset.sites.indexed.error",
) and #s("offset.sites.offset.error") percent. These site counts require
spectrum, peptide, and localization q-values at most one percent. They include
identification error and are not arrangement-level false-localization rates.

Peptide-level entrapment error was comparable between the two modes. At a
nominal one percent peptide q-value, the combined false-discovery proportion was
#s("offset.entrapment.indexed.fdp") for the expanded search over #s(
  "offset.entrapment.indexed.peptides",
) accepted paired peptides, against #s("offset.entrapment.offset.fdp") for the
offset search over #s("offset.entrapment.offset.peptides"). Both are percentages
of accepted peptides. Their difference is a few entrapment peptides at this
scale, so these searches do not establish equivalent error rates or general
calibration.

= Searching large databases <sec:large-db>

The exact prefilter extended the database sizes Sage Plus could search within
#lit("16") GiB (@fig:large-db). With the catalog at three times the human
residues, the prefilter kept #s("large.3x.kept") million of #s(
  "large.3x.streamed",
) million peptides. Peak memory was #s("large.3x.rss") GiB against #s(
  "large.3x.full.rss",
) GiB unfiltered, with wall times of #s("large.3x.minutes") and #s(
  "large.3x.full.minutes",
) minutes. At ten times, the unfiltered preflight refused the search with an
estimated #s("large.10x.full.need") GiB requirement. The prefilter search
completed at #s("large.10x.rss") GiB in #s("large.10x.minutes") minutes, keeping
#s("large.10x.kept") of #s("large.10x.streamed") million peptides.

The prefilter did not change results where both modes completed. Of #s(
  "large.pairs.compared",
) completed pairs, #s("large.pairs.identical") produced byte-identical results.
Accepted PSMs fell from #s("large.human.psms") on the human reference to #s(
  "large.10x.psms",
) at ten times, as the larger search space raised the score needed at the same
q-value. The ten-times search still accepted #s(
  "large.10x.retained",
) percent of the human-only peptides. Combined entrapment FDP stayed at #s(
  "large.1x.fdp",
), #s("large.3x.fdp"), and #s("large.10x.fdp") percent for one, three, and ten
times.

#figure(
  fig("fig.large-db", width: 100%),
  caption: [Large-database searches with the exact prefilter within a 16 GiB
    limit. A and B: peak resident memory and wall time for the HEK file against
    the human reference with gut catalog subsets, as multiples of the human
    residues. Crosses mark searches refused by the preflight or stopped by the
    memory guard. C: fraction of streamed peptides kept by the prefilter.
    Restricting the precursor to its monoisotopic mass keeps fewer. D: accepted
    human and catalog-only peptides at one percent peptide q-value, labeled with
    the combined entrapment FDP. E: accepted microbial peptides from annotated
    proteomes or six-frame genome translations, split by presence in the
    annotated proteomes. F: accepted peptides from two CAMPI fecal samples
    searched against their metagenome database. Every run appears in
    @tbl:si-large-db.],
) <fig:large-db>

Retention was set by the precursor search space rather than the database size.
The prefilter kept #s("large.3x.retention") and #s("large.10x.retention")
percent of peptides at three and ten times. With monoisotopic precursors only,
it kept #s("large.mono.10x.retention") percent at ten times, used #s(
  "large.mono.10x.rss",
) GiB, and accepted #s("large.mono.10x.psms") PSMs. The prefilter still holds
the unmodified digest while scanning. At thirty times, the memory guard stopped
the search at #s("large.30x.guard") GiB, and the monoisotopic arm was refused at
an estimated #s("large.mono.30x.need") GiB. The preflight refused the larger
subsets and the full catalog before building, estimating #s("large.100x.need")
GiB at one hundred times.

Six-frame translation searched #s("large.six.frame.peptides") million peptides
against #s("large.six.annotated.peptides") million for the annotated reference.
It accepted #s("large.six.frame.microbial") microbial peptides against #s(
  "large.six.annotated.microbial",
), with #s("large.six.shared") accepted by both. Of the six-frame peptides, #s(
  "large.six.annotated.share",
) percent occur in the annotated proteomes and #s("large.six.unannotated") do
not. These unannotated peptides are candidates, not validated novel proteins.

Both CAMPI fecal samples completed against their metagenome database, while the
unfiltered searches were refused at estimates of at least #s(
  "large.campi.F06.need",
) GiB. Sample F06 accepted #s("large.campi.F06.psms") PSMs and #s(
  "large.campi.F06.microbial",
) microbial peptides at #s("large.campi.F06.rss") GiB. Sample F05 accepted #s(
  "large.campi.F05.psms",
) PSMs and #s("large.campi.F05.microbial") microbial peptides at #s(
  "large.campi.F05.rss",
) GiB.

= Discussion <sec:discussion>

Explicit attachment identity makes modification evidence interpretable across
discovery, localization, and guided reuse. A protein coordinate and mass alone
cannot distinguish a terminal group from its neighboring residue. Keeping these
identities separate prevents one attachment from inheriting evidence for the
other. Synthetic fixtures establish this software behavior, while empirical
terminal-localization calibration remains a separate requirement.

Mass-offset search offers a complementary way to control modification-dependent
index growth. It moves work into candidate retrieval and placement scoring, so
reduced index memory can be accompanied by longer searching. The restriction to
one offset per candidate limits combinations of search-time modifications.
Indexed modifications can coexist with that offset, but the configured search
space remains part of the scientific interpretation.

Sage Plus used less peak resident memory in every completed workload. Compact
storage is a plausible contributor, but the complete-executable comparison
cannot isolate its effect from preprocessing, modeling, or execution changes.
The enlarged entrapment databases also showed that lower memory need not imply
shorter runtime. The scaling results suggest that memory savings could help when
processing several files concurrently. Testing aggregate throughput at a fixed
worker budget would establish whether that benefit occurs in practice.

The exact prefilter makes large search databases a memory question the preflight
can answer before a search starts. Because it discards only peptides that cannot
match, results were unchanged wherever both modes completed. Its reach is
bounded by two costs it does not remove. The FASTA and the unmodified digest are
still loaded in full, and retention follows the precursor window, so wide
isotope-error windows keep most of a database. Streaming the database and
narrower precursor spaces would extend the range. Metaproteomic FDP estimation
in sample-specific databases also remains outside what these searches test.

High PSM agreement and similar entrapment estimates show that the two releases
produced similar accepted identification sets and peptide-level error estimates
on the tested inputs. They do not establish identical assignments or equivalent
error rates. Some disagreements were confidence-threshold crossings, while
others changed the peptide assignment. The entrapment intervals are conditional
on the selected files and database-construction seeds, with no prespecified
equivalence margin or power analysis. Yield at matched nominal q-values should
therefore not be interpreted as yield at equal independently estimated error.
The exploratory comparison near a common estimated FDP ceiling also remains
descriptive because threshold selection reused the entrapment observations.

The LFQ comparison found nearly identical ratios on shared features, yet both
engines retained foreign-species signal in the human-only control. A precursor
confidence score shared across files does not establish confidence in each
extracted intensity. Confidence in cross-run extracted intensities needs
separate validation alongside ratio accuracy and coverage. The control cannot
detect erroneous human-to-human transfers, and contamination or reference errors
can contribute foreign signal. Its fractions are therefore diagnostics rather
than a general transfer-error rate.

The evaluation covers selected files from two public studies on one workstation.
Compute repeats and many precursor measurements do not add independent
biological studies. The selected workloads limit generalization. These datasets
also informed development and were not held out from implementation choices.
Common converted inputs leave the native readers unevaluated, while labeled
channels, library export, and automation interfaces require separate assessment.
The retention-time and final discriminant models reuse observations for fitting
and scoring, so held-out evaluation and controlled ablations remain necessary.
Sage Plus retained identifications in the restricted synthetic phosphorylation
search under the joint peptide and spectrum thresholds. Sparse decoy evidence
and unaudited acquisition-to-library mapping still limit interpretation of the
site diagnostic (@sec:si-ptm).

Sage Plus reduced memory use while maintaining similar identification and LFQ
results on the tested datasets. Runtime remains workload dependent, and
quantitative transfer confidence and PTM localization require further
validation.

// <<< BODY END



#bibliography("references.bib", title: [References], style: paper-bib-style)

// ===================== Supporting Information (appendix) =====================
// The SI is appended here as an appendix so the whole manuscript is a single
// compilation with one label namespace -- every @fig/@tbl/@sec resolves across
// the main text and the SI, and numbers can never drift out of sync.
// From this point on, figures and tables restart at S1, S2, ... and SI headings
// number S1, S2, ...  (page and line numbering stay continuous.)
#pagebreak()

#counter(figure.where(kind: image)).update(0)
#counter(figure.where(kind: table)).update(0)
#counter(heading).update(0)
#show figure.where(kind: image): set figure(numbering: n => "S" + str(n))
#show figure.where(kind: table): set figure(numbering: n => "S" + str(n))
#set heading(numbering: (..n) => "S" + n.pos().map(str).join("."))

// Same trap as any centred block: HTML export discards the align/block wrapper AND
// its contents, so on the Word path this whole title block vanishes and the main
// text runs straight into Section S1 with nothing marking the boundary. Emit it as
// plain content there -- a real heading, so it also lands in Word's navigation pane
// -- and keep the centred layout for the PDF.
#if docx-mode [
  #heading(level: 1, numbering: none, outlined: false)[Supporting Information]

  #text(13pt)[#paper-title]

  #text(10pt, style: "italic")[#si-authors]
] else [
  #align(center)[
    #text(15pt, weight: "bold")[Supporting Information]
    #v(2pt)
    #text(13pt)[#paper-title]
    #v(2pt)
    #text(10pt, style: "italic")[#si-authors]
  ]

  #v(1em)
]

#include "si-body.typ"
